import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {Readable,Writable} from 'node:stream';
import {createAuth} from '../portfolio-auth.mjs';
import {handleWebsiteRequest} from '../website-routing.mjs';
const json=(res,status,data,headers={})=>{res.writeHead(status,headers);res.end(JSON.stringify(data))};
function call(handler,pathname,body,cookie=''){return new Promise((resolve,reject)=>{const req=Readable.from(body?[Buffer.from(JSON.stringify(body))]:[]);req.headers={cookie};req.method=body?'POST':'GET';req.socket={remoteAddress:'test'};let status=200,headers={};const chunks=[];const res=new Writable({write(c,e,done){chunks.push(c);done()}});res.writeHead=(s,h)=>{status=s;headers=h};res.on('finish',()=>resolve({status,headers,body:Buffer.concat(chunks).toString()}));Promise.resolve(handler(req,res,new URL(pathname,'http://localhost'))).catch(reject)})}
test('removed vehicle pages and APIs return 404 without cross-domain redirects',async()=>{for(const p of ['/car','/cars','/cars/account','/vehicles','/api/private/vehicles','/api/admin/vehicle-portal','/admin/vehicle-portal','/api/auth/register','/garifile.html']){const result=await call(handleWebsiteRequest,p);assert.equal(result.status,404,p);assert.equal(result.headers.Location,undefined)}});
test('portfolio auth uses independent admin-only sessions',async()=>{const db=new DatabaseSync(':memory:');db.exec('CREATE TABLE sessions(token_hash TEXT PRIMARY KEY,expires_at INTEGER NOT NULL)');const oldEmail=process.env.ADMIN_EMAIL,oldPassword=process.env.ADMIN_PASSWORD;process.env.ADMIN_EMAIL='admin@example.test';process.env.ADMIN_PASSWORD='test-portfolio-password';try{const auth=await createAuth({db,json});const login=await call(auth.api,'/api/login',{email:'admin@example.test',password:'test-portfolio-password'});assert.equal(login.status,200);const cookie=login.headers['Set-Cookie'].split(';')[0];assert.ok(cookie.startsWith('portfolio_session='));assert.equal((await call(auth.api,'/api/auth/me',null,cookie)).status,200);assert.equal((await call(auth.api,'/api/auth/me',null,cookie.replace('portfolio_session=','garifile_session='))).status,401);assert.equal((await call(auth.api,'/api/auth/me',null,cookie.replace('portfolio_session=','vj_session='))).status,401);await call(auth.api,'/api/logout',null,cookie);assert.equal((await call(auth.api,'/api/auth/me',null,cookie)).status,401);assert.deepEqual(db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name LIKE 'vehicle%'").all(),[])}finally{db.close();if(oldEmail===undefined)delete process.env.ADMIN_EMAIL;else process.env.ADMIN_EMAIL=oldEmail;if(oldPassword===undefined)delete process.env.ADMIN_PASSWORD;else process.env.ADMIN_PASSWORD=oldPassword}});
