import crypto from "node:crypto";
import {createSmtpTransport,mailFrom,smtpConfigured} from "./mailer.mjs";
import {promisify} from "node:util";

const scrypt=promisify(crypto.scrypt), clean=(v="",n=200)=>String(v??"").replace(/[<>]/g,"").trim().slice(0,n), hash=s=>crypto.createHash("sha256").update(s).digest("hex");
const addColumn=(db,table,name,definition)=>{const columns=new Set(db.prepare(`PRAGMA table_info(${table})`).all().map(row=>row.name));if(!columns.has(name))db.exec(`ALTER TABLE ${table} ADD COLUMN ${name} ${definition}`)};
const cookies=req=>Object.fromEntries((req.headers.cookie||"").split(";").filter(Boolean).map(x=>{const i=x.indexOf("=");return[x.slice(0,i).trim(),decodeURIComponent(x.slice(i+1))]}));
async function passwordHash(password){const salt=crypto.randomBytes(16).toString("hex"),derived=await scrypt(password,salt,64);return`scrypt$${salt}$${Buffer.from(derived).toString("hex")}`}
async function passwordOk(password,stored){const[,salt,wanted]=String(stored||"").split("$");if(!salt||!wanted)return false;const got=Buffer.from(await scrypt(password,salt,64)),target=Buffer.from(wanted,"hex");return got.length===target.length&&crypto.timingSafeEqual(got,target)}

export async function createAuth({db,json}){
 db.exec(`CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,email TEXT NOT NULL COLLATE NOCASE UNIQUE,password_hash TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'user' CHECK(role IN ('user','admin')),active INTEGER NOT NULL DEFAULT 1,force_password_reset INTEGER NOT NULL DEFAULT 0,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP); CREATE INDEX IF NOT EXISTS idx_users_active ON users(active); CREATE TABLE IF NOT EXISTS password_reset_tokens(token_hash TEXT PRIMARY KEY,user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,expires_at INTEGER NOT NULL,used_at INTEGER,created_at TEXT DEFAULT CURRENT_TIMESTAMP); CREATE INDEX IF NOT EXISTS idx_reset_expiry ON password_reset_tokens(expires_at); CREATE TABLE IF NOT EXISTS managed_user_audit(id INTEGER PRIMARY KEY AUTOINCREMENT,actor_user_id INTEGER,user_id INTEGER,action TEXT NOT NULL,details TEXT DEFAULT '',created_at TEXT DEFAULT CURRENT_TIMESTAMP); CREATE INDEX IF NOT EXISTS idx_managed_audit_actor ON managed_user_audit(actor_user_id,created_at DESC);`);
 addColumn(db,"users","mobile","TEXT DEFAULT ''");addColumn(db,"users","account_kind","TEXT NOT NULL DEFAULT 'customer'");addColumn(db,"users","organization_name","TEXT DEFAULT ''");addColumn(db,"users","date_of_birth","TEXT DEFAULT ''");addColumn(db,"users","designation","TEXT DEFAULT ''");addColumn(db,"users","address","TEXT DEFAULT ''");addColumn(db,"users","city","TEXT DEFAULT ''");addColumn(db,"users","state","TEXT DEFAULT ''");addColumn(db,"users","postal_code","TEXT DEFAULT ''");addColumn(db,"users","created_by_user_id","INTEGER REFERENCES users(id)");addColumn(db,"users","last_login_at","TEXT");addColumn(db,"users","invitation_status","TEXT DEFAULT ''");addColumn(db,"users","invitation_sent_at","TEXT");
 db.exec("UPDATE users SET organization_name=name WHERE role='user' AND COALESCE(account_kind,'customer')='customer' AND (organization_name IS NULL OR organization_name='')");
 const sessionColumns=new Set(db.prepare("PRAGMA table_info(sessions)").all().map(x=>x.name));if(!sessionColumns.has("user_id"))db.exec("ALTER TABLE sessions ADD COLUMN user_id INTEGER REFERENCES users(id) ON DELETE CASCADE");
 const adminEmail=String(process.env.ADMIN_EMAIL||"").trim().toLowerCase(),adminPassword=String(process.env.ADMIN_PASSWORD||"");let owner=db.prepare("SELECT * FROM users WHERE role='admin' ORDER BY id LIMIT 1").get();
 if(!owner&&adminEmail&&adminPassword.length>=12){db.prepare("INSERT INTO users(name,email,password_hash,role) VALUES(?,?,?,'admin')").run("Site Administrator",adminEmail,await passwordHash(adminPassword));owner=db.prepare("SELECT * FROM users WHERE email=?").get(adminEmail)}
 const currentUser=req=>{const token=cookies(req).vj_session;if(!token)return null;db.prepare("DELETE FROM sessions WHERE expires_at < ?").run(Date.now());return db.prepare("SELECT u.id,u.name,u.email,u.mobile,u.organization_name,u.date_of_birth,u.designation,u.address,u.city,u.state,u.postal_code,u.role,u.account_kind,u.created_by_user_id,u.active,u.force_password_reset,u.last_login_at FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>? AND u.active=1").get(hash(token),Date.now())||null};
 const authed=req=>!!currentUser(req),admin=req=>currentUser(req)?.role==="admin";
 const issueSession=(res,user)=>{const token=crypto.randomBytes(32).toString("hex");db.prepare("INSERT INTO sessions(token_hash,expires_at,user_id) VALUES(?,?,?)").run(hash(token),Date.now()+7*864e5,user.id);return json(res,200,{ok:true,user:{id:user.id,name:user.name,email:user.email,mobile:user.mobile||"",role:user.role,accountKind:user.account_kind||"customer",forcePasswordReset:!!user.force_password_reset}},{"Set-Cookie":`vj_session=${token}; HttpOnly; SameSite=Strict; Path=/; Max-Age=604800${process.env.NODE_ENV==="production"?"; Secure":""}`})};
 const read=async req=>{const chunks=[];for await(const c of req)chunks.push(c);return JSON.parse(Buffer.concat(chunks).toString()||"{}")};
 const attempts=new Map(),throttle=(key,limit=8)=>{const now=Date.now(),a=attempts.get(key)||[];const recent=a.filter(t=>now-t<15*60e3);recent.push(now);attempts.set(key,recent);return recent.length>limit};
 const sendReset=async(user,token)=>{if(!smtpConfigured())return false;const transport=createSmtpTransport(),base=process.env.APP_BASE_URL||"https://vijayjha.in";try{await transport.sendMail({from:mailFrom(),to:user.email,subject:"Reset your GaadiFile password",text:`Open this secure link to reset your GaadiFile password: ${base}/vehicles?reset=${encodeURIComponent(token)}\n\nThis link expires in 30 minutes.`});return true}finally{transport.close()}};
 const temporaryPassword=()=>`${crypto.randomBytes(9).toString("base64url")}A1!`;
 const auditManaged=(actorId,userId,action,details="")=>db.prepare("INSERT INTO managed_user_audit(actor_user_id,user_id,action,details) VALUES(?,?,?,?)").run(actorId,userId,action,clean(details,1000));
 const sendInvitation=async(user,password,access)=>{if(!smtpConfigured())return false;const transport=createSmtpTransport(),base=String(process.env.APP_BASE_URL||"https://vijayjha.in").replace(/\/$/,"");try{await transport.sendMail({from:mailFrom(),to:user.email,subject:"Your GaadiFile Login Details",text:`Hello ${user.name},\n\nYour GaadiFile account has been created.\n\nLogin URL:\n${base}/login\n\nEmail:\n${user.email}\n\nTemporary Password:\n${password}\n\nAccess:\n${access.permission==="editor"?"Editor":"View Only"}\n\nLocation:\n${access.locationName}\n\nVehicles:\n${access.scope==="location"?"All vehicles":access.vehicleNumbers.join(", ")}\n\nFor security, please change your password after first login.\n\nRegards,\nGaadiFile`});return true}finally{transport.close()}};
 async function api(req,res,url){
  if(url.pathname==="/api/auth/register"&&req.method==="POST"){if(throttle(`register:${req.socket.remoteAddress}`))return json(res,429,{error:"Too many requests"});const b=await read(req),name=clean(b.name,100),organizationName=clean(b.organizationName||b.organization_name||name,160),email=clean(b.email,254).toLowerCase(),password=String(b.password||"");if(!name||!/^\S+@\S+\.\S+$/.test(email)||password.length<12)return json(res,400,{error:"Name, valid email and password of at least 12 characters are required"});try{const r=db.prepare("INSERT INTO users(name,email,password_hash,organization_name) VALUES(?,?,?,?)").run(name,email,await passwordHash(password),organizationName),user=db.prepare("SELECT * FROM users WHERE id=?").get(Number(r.lastInsertRowid));return issueSession(res,user)}catch(e){return json(res,409,{error:"An account with this email already exists"})}}
  if(url.pathname==="/api/login"&&req.method==="POST"){if(throttle(`login:${req.socket.remoteAddress}`))return json(res,429,{error:"Too many attempts. Try again later."});const b=await read(req),user=db.prepare("SELECT * FROM users WHERE email=?").get(clean(b.email,254).toLowerCase());if(!user||!user.active||!await passwordOk(String(b.password||""),user.password_hash))return json(res,401,{error:"Email or password is incorrect"});db.prepare("UPDATE users SET last_login_at=CURRENT_TIMESTAMP WHERE id=?").run(user.id);auditManaged(user.id,user.id,"user_login");return issueSession(res,user)}
  if(url.pathname==="/api/auth/me"&&req.method==="GET"){const user=currentUser(req);return user?json(res,200,{user}):json(res,401,{error:"Login required"})}
  if(url.pathname==="/api/auth/profile"&&req.method==="PUT"){const user=currentUser(req);if(!user)return json(res,401,{error:"Login required"});const b=await read(req),name=clean(b.name,100),email=clean(b.email,254).toLowerCase(),mobile=clean(b.mobile,30),organizationName=clean(b.organization_name,160),dateOfBirth=clean(b.date_of_birth,10),designation=clean(b.designation,120),address=clean(b.address,500),city=clean(b.city,100),state=clean(b.state,100),postalCode=clean(b.postal_code,20),birthTime=dateOfBirth?Date.parse(`${dateOfBirth}T00:00:00Z`):0;if(!name||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return json(res,400,{error:"Name and a valid email address are required"});if(dateOfBirth&&(!/^\d{4}-\d{2}-\d{2}$/.test(dateOfBirth)||!Number.isFinite(birthTime)||new Date(birthTime).toISOString().slice(0,10)!==dateOfBirth||birthTime>Date.now()))return json(res,400,{error:"Date of birth must be a valid past date"});try{db.prepare("UPDATE users SET name=?,email=?,mobile=?,organization_name=?,date_of_birth=?,designation=?,address=?,city=?,state=?,postal_code=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(name,email,mobile,organizationName,dateOfBirth,designation,address,city,state,postalCode,user.id);auditManaged(user.id,user.id,"profile_updated");return json(res,200,{ok:true,user:currentUser(req)})}catch(error){if(String(error.message).includes("UNIQUE constraint failed"))return json(res,409,{error:"An account with this email already exists"});throw error}}
  if(url.pathname==="/api/logout"){const token=cookies(req).vj_session;if(token)db.prepare("DELETE FROM sessions WHERE token_hash=?").run(hash(token));res.writeHead(302,{Location:"/","Set-Cookie":"vj_session=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0"});return res.end()}
  if(url.pathname==="/api/auth/forgot-password"&&req.method==="POST"){const b=await read(req),user=db.prepare("SELECT * FROM users WHERE email=? AND active=1").get(clean(b.email,254).toLowerCase());if(user&&!throttle(`reset:${user.id}`,3)){const token=crypto.randomBytes(32).toString("hex");db.prepare("DELETE FROM password_reset_tokens WHERE user_id=? OR expires_at<?").run(user.id,Date.now());db.prepare("INSERT INTO password_reset_tokens(token_hash,user_id,expires_at) VALUES(?,?,?)").run(hash(token),user.id,Date.now()+30*60e3);await sendReset(user,token).catch(()=>false)}return json(res,200,{ok:true,message:"If that account exists, a reset link has been sent."})}
  if(url.pathname==="/api/auth/reset-password"&&req.method==="POST"){const b=await read(req),password=String(b.password||""),row=db.prepare("SELECT * FROM password_reset_tokens WHERE token_hash=? AND used_at IS NULL AND expires_at>?").get(hash(String(b.token||"")),Date.now());if(!row||password.length<12)return json(res,400,{error:"Reset link is invalid or expired, or password is too short"});db.exec("BEGIN");try{db.prepare("UPDATE users SET password_hash=?,force_password_reset=0,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(await passwordHash(password),row.user_id);db.prepare("UPDATE password_reset_tokens SET used_at=? WHERE token_hash=?").run(Date.now(),row.token_hash);db.prepare("DELETE FROM sessions WHERE user_id=?").run(row.user_id);db.exec("COMMIT")}catch(e){db.exec("ROLLBACK");throw e}return json(res,200,{ok:true})}
  if(url.pathname==="/api/auth/change-password"&&req.method==="POST"){const user=currentUser(req);if(!user)return json(res,401,{error:"Login required"});const b=await read(req),full=db.prepare("SELECT * FROM users WHERE id=?").get(user.id);if(!await passwordOk(String(b.currentPassword||""),full.password_hash)||String(b.newPassword||"").length<12)return json(res,400,{error:"Current password is incorrect or new password is too short"});db.prepare("UPDATE users SET password_hash=?,force_password_reset=0,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(await passwordHash(String(b.newPassword)),user.id);auditManaged(user.id,user.id,"password_changed");return json(res,200,{ok:true})}
  if(url.pathname==="/api/admin/vehicle-users"&&req.method==="GET"){if(!admin(req))return json(res,403,{error:"Administrator access required"});const users=db.prepare("SELECT u.id,u.name,u.email,u.role,u.active,u.force_password_reset,u.created_at,COUNT(DISTINCT v.id) vehicles FROM users u LEFT JOIN vehicles v ON v.user_id=u.id GROUP BY u.id ORDER BY u.created_at DESC").all(),summary=db.prepare("SELECT (SELECT COUNT(*) FROM users) totalUsers,(SELECT COUNT(*) FROM users WHERE active=1) activeUsers,(SELECT COUNT(*) FROM users WHERE active=0) disabledUsers,(SELECT COUNT(*) FROM vehicles) totalVehicles,(SELECT COUNT(*) FROM vehicle_documents WHERE deleted_at IS NULL) totalDocuments,(SELECT COALESCE(SUM(file_size),0) FROM document_versions WHERE is_active=1 AND deleted_at IS NULL) storageBytes").get();return json(res,200,{users,summary})}
  const um=url.pathname.match(/^\/api\/admin\/vehicle-users\/(\d+)$/);if(um&&req.method==="PATCH"){if(!admin(req))return json(res,403,{error:"Administrator access required"});const actor=currentUser(req),id=Number(um[1]),b=await read(req);if(id===actor.id&&(b.active===false||b.forcePasswordReset))return json(res,400,{error:"You cannot lock your own administrator account"});if(typeof b.active==="boolean")db.prepare("UPDATE users SET active=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(b.active?1:0,id);if(b.forcePasswordReset)db.prepare("UPDATE users SET force_password_reset=1,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(id);if(b.active===false||b.forcePasswordReset)db.prepare("DELETE FROM sessions WHERE user_id=?").run(id);return json(res,200,{ok:true})}
  return false;
 }
 return{api,currentUser,authed,admin,ownerUserId:owner?.id||null,managed:{passwordHash,temporaryPassword,sendInvitation,audit:auditManaged}};
}
