import http from "node:http";
import { readFile, mkdir, writeFile, readdir } from "node:fs/promises";
import { createReadStream, existsSync } from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import { Readable } from "node:stream";
import { DatabaseSync } from "node:sqlite";
import { createServer as createViteServer } from "vite";
import { createVehicleApi } from "./vehicle-api.mjs";
import { createAuth } from "./auth-api.mjs";
import { createVehicleSharing } from "./vehicle-sharing.mjs";

const root=process.cwd(), dataDir=path.join(root,"data"), uploadDir=path.join(dataDir,"uploads");
await mkdir(uploadDir,{recursive:true});
const db=new DatabaseSync(path.join(dataDir,"site.db"));
db.exec(`PRAGMA busy_timeout=10000; PRAGMA journal_mode=WAL; CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT NOT NULL); CREATE TABLE IF NOT EXISTS posts(id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT NOT NULL,slug TEXT UNIQUE NOT NULL,category TEXT NOT NULL,excerpt TEXT NOT NULL,content TEXT NOT NULL,image TEXT DEFAULT '',published INTEGER DEFAULT 1,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP); CREATE INDEX IF NOT EXISTS idx_posts_published_created ON posts(published,created_at); CREATE TABLE IF NOT EXISTS sessions(token_hash TEXT PRIMARY KEY,expires_at INTEGER NOT NULL); CREATE INDEX IF NOT EXISTS idx_sessions_expiry ON sessions(expires_at); CREATE TABLE IF NOT EXISTS messages(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,email TEXT NOT NULL,phone TEXT DEFAULT '',message TEXT NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP);`);
db.exec(`CREATE TABLE IF NOT EXISTS instagram_posts(id TEXT PRIMARY KEY,media_type TEXT NOT NULL,media_url TEXT NOT NULL,thumbnail_url TEXT DEFAULT '',permalink TEXT NOT NULL,caption TEXT DEFAULT '',posted_at TEXT DEFAULT '',synced_at TEXT DEFAULT CURRENT_TIMESTAMP); CREATE INDEX IF NOT EXISTS idx_instagram_posts_posted ON instagram_posts(posted_at DESC);`);
const postColumns={tags:"TEXT DEFAULT ''",author:"TEXT DEFAULT 'Vijay Jha'",publish_date:"TEXT DEFAULT ''",canonical_url:"TEXT DEFAULT ''",seo_title:"TEXT DEFAULT ''",meta_description:"TEXT DEFAULT ''",og_title:"TEXT DEFAULT ''",og_description:"TEXT DEFAULT ''",og_image:"TEXT DEFAULT ''",faqs_json:"TEXT DEFAULT '[]'",related_posts_json:"TEXT DEFAULT '[]'",related_keywords_json:"TEXT DEFAULT '[]'",read_time:"INTEGER DEFAULT 1",focus_keyword:"TEXT DEFAULT ''",featured:"INTEGER DEFAULT 0",image_alt:"TEXT DEFAULT ''",image_caption:"TEXT DEFAULT ''"};
const existingColumns=new Set(db.prepare("PRAGMA table_info(posts)").all().map(x=>x.name));for(const[name,definition]of Object.entries(postColumns))if(!existingColumns.has(name))db.exec(`ALTER TABLE posts ADD COLUMN ${name} ${definition}`);
const seed={name:"Vijay Jha",hero_overline:"TAX • STARTUPS • INVESTMENT",hero_title:"Tax. Startups. Investment.",hero_subtitle:"Clarity for business. Confidence for growth.",service_1_title:"Tax Consultant",service_1_text:"Clear tax planning, compliance and practical advisory for individuals and businesses.",service_2_title:"Startup Advisor",service_2_text:"Structure, strategy and grounded guidance for founders building from idea to scale.",service_3_title:"Investor",service_3_text:"Thoughtful capital, due diligence and long-term partnership with promising ventures.",interest_title:"Travel & Machines",interest_text:"Motorcycles, cars and journeys that bring fresh perspective.",about_title:"Law. Numbers. Strategy. Impact.",about_text:"I am an LLB graduate, tax consultant, startup advisor and investor. I help individuals, businesses and founders navigate complexity, make smarter decisions and build for the long term.",contact_title:"Let’s talk about your next move.",contact_text:"For tax consulting, startup guidance, investment conversations or collaborations.",email:"hello@vijayjha.in",phone:"",location:"India",profile_image:""};
Object.assign(seed,{hero_role:"Tax Consultant • Startup Advisor • Investor",work_json:"[]",skills_json:"[]",experience_json:"[]",hobbies_json:"[]",gallery_json:"[]",social_json:"[]"});
Object.assign(seed,{instagram_profile:"",instagram_enabled:"0",instagram_count:"6",instagram_last_sync:"",instagram_sync_status:"Not synced yet"});
Object.assign(seed,{brand_name:"VIJAY JHA",nav_home:"HOME",nav_about:"ABOUT",nav_blog:"BLOG",nav_contact:"CONTACT",hero_primary_button:"Explore my work",hero_secondary_button:"Contact me",about_label:"ABOUT",about_statement:"I help people make better decisions when the stakes are high.",stat_1_value:"10+",stat_1_label:"YEARS EXPERIENCE",stat_2_value:"120+",stat_2_label:"CLIENTS ADVISED",stat_3_value:"18+",stat_3_label:"STARTUPS GUIDED",work_label:"WORK",work_title:"Measured thinking. Meaningful outcomes.",skills_label:"SKILLS",skills_title:"Depth where it matters.",experience_label:"EXPERIENCE",experience_title:"Experience, built deliberately.",beyond_label:"BEYOND WORK",beyond_title:"Curiosity keeps me moving.",gallery_label:"PERSONAL ARCHIVE",gallery_title:"Moments beyond the numbers.",gallery_text:"A growing collection of places, people and perspectives.",blog_label:"NOTES & PERSPECTIVES",blog_title:"Thinking in public.",blog_empty_title:"The journal is taking shape.",blog_empty_text:"New observations will appear here soon.",contact_label:"START A CONVERSATION",footer_copyright:"© 2026 Vijay Jha",footer_roles:"Tax Consultant • Startup Advisor • Investor",footer_home:"Home ↑"});
Object.assign(seed,{blog_breadcrumb:"Journal",blog_faq_label:"FREQUENTLY ASKED QUESTIONS",blog_faq_title:"FAQs",blog_related_label:"KEEP READING",blog_related_title:"Related posts"});
Object.assign(seed,{brand_initials:"VJ",blog_index:"JOURNAL",blog_read_suffix:"min read",blog_read_article:"Read article",blog_loading:"Loading article…",contact_email_label:"Email",contact_instagram_label:"Instagram"});
const insertSetting=db.prepare("INSERT OR IGNORE INTO settings(key,value) VALUES(?,?)");for(const [k,v] of Object.entries(seed))insertSetting.run(k,v);
const settings=()=>Object.fromEntries(db.prepare("SELECT key,value FROM settings").all().map(x=>[x.key,x.value]));
const json=(res,status,data,headers={})=>{res.writeHead(status,{"Content-Type":"application/json; charset=utf-8",...headers});res.end(JSON.stringify(data))};
const body=async req=>{const chunks=[];for await(const c of req)chunks.push(c);return JSON.parse(Buffer.concat(chunks).toString()||"{}")} ;
const safe=(s="")=>String(s).replace(/[<>]/g,"").trim();
const slugify=s=>safe(s).toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")||"post";
const uniqueSlug=(wanted,id=0)=>{const base=slugify(wanted);let candidate=base,n=2;while(db.prepare("SELECT 1 FROM posts WHERE slug=? AND id<>?").get(candidate,id))candidate=`${base}-${n++}`;return candidate};
async function formData(req){const request=new Request(`http://localhost${req.url}`,{method:req.method,headers:req.headers,body:Readable.toWeb(req),duplex:"half"});return request.formData()}
async function saveUpload(file,prefix){if(!file||typeof file==="string"||!file.size)return "";if(file.size>8*1024*1024)throw new Error("Image must be smaller than 8MB");if(!String(file.type).startsWith("image/"))throw new Error("Only image uploads are allowed");const ext={"image/jpeg":"jpg","image/png":"png","image/webp":"webp","image/gif":"gif"}[file.type]||"img";const name=`${prefix}-${Date.now()}-${crypto.randomBytes(4).toString("hex")}.${ext}`;await writeFile(path.join(uploadDir,name),Buffer.from(await file.arrayBuffer()));return `/uploads/${name}`}
const instagramSettings=()=>{const s=settings(),count=[6,9,12].includes(Number(s.instagram_count))?Number(s.instagram_count):6;return{enabled:s.instagram_enabled==="1",profile:s.instagram_profile||"",count,lastSync:s.instagram_last_sync||"",status:s.instagram_sync_status||"Not synced yet"}};
const cachedInstagramPosts=count=>db.prepare("SELECT id,media_type,media_url,thumbnail_url,permalink,caption,posted_at FROM instagram_posts ORDER BY posted_at DESC LIMIT ?").all(count);
async function syncInstagram(count){const token=process.env.INSTAGRAM_ACCESS_TOKEN,userId=process.env.INSTAGRAM_USER_ID,version=process.env.INSTAGRAM_GRAPH_VERSION||"v25.0";if(!token||!userId)throw new Error("Instagram credentials are not configured on the server");const fields="id,caption,media_type,media_url,thumbnail_url,permalink,timestamp,children{media_type,media_url,thumbnail_url}",endpoint=`https://graph.instagram.com/${version}/${encodeURIComponent(userId)}/media?fields=${encodeURIComponent(fields)}&limit=${count}&access_token=${encodeURIComponent(token)}`,response=await fetch(endpoint,{headers:{Accept:"application/json"}}),payload=await response.json();if(!response.ok)throw new Error(payload?.error?.message||`Instagram API returned ${response.status}`);const rows=(payload.data||[]).filter(x=>["IMAGE","CAROUSEL_ALBUM"].includes(x.media_type)).slice(0,count),up=db.prepare("INSERT INTO instagram_posts(id,media_type,media_url,thumbnail_url,permalink,caption,posted_at,synced_at) VALUES(?,?,?,?,?,?,?,CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET media_type=excluded.media_type,media_url=excluded.media_url,thumbnail_url=excluded.thumbnail_url,permalink=excluded.permalink,caption=excluded.caption,posted_at=excluded.posted_at,synced_at=CURRENT_TIMESTAMP");db.exec("BEGIN");try{for(const item of rows){const child=item.children?.data?.find(x=>x.media_url||x.thumbnail_url),media=item.media_url||child?.media_url||child?.thumbnail_url||"",thumb=item.thumbnail_url||child?.thumbnail_url||child?.media_url||media;if(media)up.run(String(item.id),String(item.media_type),String(media),String(thumb),String(item.permalink||""),String(item.caption||"").slice(0,4000),String(item.timestamp||""))}db.exec("COMMIT")}catch(error){db.exec("ROLLBACK");throw error}return rows.length}
const auth=await createAuth({db,json});
const vehicleSharing=createVehicleSharing({db,currentUser:auth.currentUser,json,managed:auth.managed});
const vehicleApi=await createVehicleApi({db,root,authed:auth.authed,currentUser:auth.currentUser,ownerUserId:auth.ownerUserId,json,sharing:vehicleSharing});
async function api(req,res,url){
 const authResponse=await auth.api(req,res,url);if(authResponse!==false)return authResponse;
 if(url.pathname.startsWith("/api/private/vehicles"))return vehicleApi(req,res,url);
 if(url.pathname==="/api/content"&&req.method==="GET"){const ig=instagramSettings();return json(res,200,{settings:settings(),posts:db.prepare("SELECT * FROM posts WHERE published=1 AND (publish_date='' OR datetime(publish_date)<=datetime('now','localtime')) ORDER BY COALESCE(NULLIF(publish_date,''),created_at) DESC").all(),instagram:{...ig,posts:ig.enabled?cachedInstagramPosts(ig.count):[]}})}
 const publicPost=url.pathname.match(/^\/api\/posts\/([a-z0-9-]+)$/);if(publicPost&&req.method==="GET"){const post=db.prepare("SELECT * FROM posts WHERE slug=? AND published=1 AND (publish_date='' OR datetime(publish_date)<=datetime('now','localtime'))").get(publicPost[1]);return post?json(res,200,{post}):json(res,404,{error:"Post not found"})}
 const previewPost=url.pathname.match(/^\/api\/preview\/(\d+)$/);if(previewPost&&req.method==="GET"){if(!auth.admin(req))return json(res,401,{error:"Administrator login required"});const post=db.prepare("SELECT * FROM posts WHERE id=?").get(Number(previewPost[1]));return post?json(res,200,{post}):json(res,404,{error:"Post not found"})}
 if(url.pathname.startsWith("/api/admin/")&&!auth.admin(req))return json(res,401,{error:"Administrator login required"});
 if(url.pathname==="/api/admin/state"&&req.method==="GET")return json(res,200,{settings:settings(),posts:db.prepare("SELECT * FROM posts ORDER BY created_at DESC").all(),messages:db.prepare("SELECT * FROM messages ORDER BY created_at DESC LIMIT 100").all()});
 if(url.pathname==="/api/admin/media"&&req.method==="GET"){const files=(await readdir(uploadDir,{withFileTypes:true})).filter(x=>x.isFile()&&/\.(jpe?g|png|webp|gif)$/i.test(x.name)).map(x=>({name:x.name,url:`/uploads/${x.name}`})).reverse();return json(res,200,{files})}
 if(url.pathname==="/api/admin/post-meta"&&req.method==="POST"){const b=await body(req);db.prepare("UPDATE posts SET focus_keyword=?,featured=?,image_alt=?,image_caption=? WHERE slug=?").run(safe(b.focus_keyword),b.featured?1:0,safe(b.image_alt),safe(b.image_caption),safe(b.slug));return json(res,200,{ok:true})}
 if(url.pathname==="/api/admin/settings"&&req.method==="POST"){try{const fd=await formData(req),up=db.prepare("INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value");for(const k of Object.keys(seed))if(k!=="profile_image"&&fd.has(k))up.run(k,String(fd.get(k)).slice(0,100000));const img=await saveUpload(fd.get("profile"),"profile");if(img)up.run("profile_image",img);let gallery=JSON.parse(String(fd.get("gallery_json")||settings().gallery_json||"[]"));for(let i=0;i<gallery.length;i++){const uploaded=await saveUpload(fd.get(`gallery_${i}`),`gallery-${i}`);if(uploaded)gallery[i].src=uploaded}up.run("gallery_json",JSON.stringify(gallery));return json(res,200,{ok:true})}catch(e){return json(res,400,{error:e.message})}}
 if(url.pathname==="/api/admin/instagram/sync"&&req.method==="POST"){const up=db.prepare("INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value");try{const b=await body(req),count=[6,9,12].includes(Number(b.count))?Number(b.count):6;up.run("instagram_profile",safe(b.profile));up.run("instagram_enabled",b.enabled?"1":"0");up.run("instagram_count",String(count));const synced=await syncInstagram(count),now=new Date().toISOString(),status=`Synced ${synced} posts`;up.run("instagram_last_sync",now);up.run("instagram_sync_status",status);return json(res,200,{ok:true,count:synced,lastSync:now,status})}catch(e){const status=`Sync failed: ${String(e.message).slice(0,180)}`;up.run("instagram_sync_status",status);return json(res,400,{error:e.message,status,cached:Number(db.prepare("SELECT COUNT(*) total FROM instagram_posts").get().total)})}}
 if(url.pathname==="/api/admin/posts"&&req.method==="POST"){try{const fd=await formData(req),id=Number(fd.get("id"))||0,old=id?db.prepare("SELECT * FROM posts WHERE id=?").get(id):null,img=await saveUpload(fd.get("image"),"post")||(old?.image||""),ogUpload=await saveUpload(fd.get("og_image_upload"),"post-og"),title=safe(fd.get("title")),slug=uniqueSlug(String(fd.get("slug")||title),id),published=Number(fd.get("published"))?1:0;const vals={title,slug,category:safe(fd.get("category"))||"Insights",excerpt:safe(fd.get("excerpt")),content:String(fd.get("content")||"").trim().slice(0,500000),image:img,published,tags:safe(fd.get("tags")),author:safe(fd.get("author"))||"Vijay Jha",publish_date:safe(fd.get("publish_date")),canonical_url:safe(fd.get("canonical_url")),seo_title:safe(fd.get("seo_title")),meta_description:safe(fd.get("meta_description")),og_title:safe(fd.get("og_title")),og_description:safe(fd.get("og_description")),og_image:ogUpload||safe(fd.get("og_image"))||(old?.og_image||""),faqs_json:String(fd.get("faqs_json")||"[]"),related_posts_json:String(fd.get("related_posts_json")||"[]"),related_keywords_json:String(fd.get("related_keywords_json")||"[]"),read_time:Math.max(1,Number(fd.get("read_time"))||1)};JSON.parse(vals.faqs_json);JSON.parse(vals.related_posts_json);JSON.parse(vals.related_keywords_json);if(!vals.title||!vals.content)throw new Error("Title and content are required");const keys=Object.keys(vals),values=Object.values(vals);if(id)db.prepare(`UPDATE posts SET ${keys.map(k=>`${k}=?`).join(",")},updated_at=CURRENT_TIMESTAMP WHERE id=?`).run(...values,id);else db.prepare(`INSERT INTO posts(${keys.join(",")}) VALUES(${keys.map(()=>"?").join(",")})`).run(...values);return json(res,200,{ok:true,slug})}catch(e){return json(res,400,{error:e.message})}}
 const pm=url.pathname.match(/^\/api\/admin\/posts\/(\d+)$/);if(pm&&req.method==="DELETE"){db.prepare("DELETE FROM posts WHERE id=?").run(Number(pm[1]));return json(res,200,{ok:true})}
 if(url.pathname==="/api/contact"&&req.method==="POST"){const b=await body(req);if(!b.name||!b.email||!b.message)return json(res,400,{error:"Please complete the required fields"});db.prepare("INSERT INTO messages(name,email,phone,message) VALUES(?,?,?,?)").run(safe(b.name),safe(b.email),safe(b.phone),safe(b.message));return json(res,200,{ok:true})}
 return false;
}

const prod=process.env.NODE_ENV==="production";const vite=prod?null:await createViteServer({server:{middlewareMode:true},appType:"spa"});
const mime={".js":"text/javascript",".css":"text/css",".html":"text/html",".png":"image/png",".jpg":"image/jpeg",".jpeg":"image/jpeg",".webp":"image/webp",".svg":"image/svg+xml"};
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,"http://localhost");if(url.pathname.startsWith("/api/")){if(await api(req,res,url)!==false)return}if(url.pathname.startsWith("/uploads/")){const p=path.join(uploadDir,path.basename(url.pathname));if(!existsSync(p)){res.writeHead(404);return res.end()}res.writeHead(200,{"Content-Type":mime[path.extname(p)]||"application/octet-stream","Cache-Control":"public,max-age=31536000,immutable"});return createReadStream(p).pipe(res)}if(vite)return vite.middlewares(req,res,()=>{});let file=url.pathname.includes(".")?path.join(root,"dist",url.pathname):path.join(root,"dist","index.html");if(!existsSync(file))file=path.join(root,"dist","index.html");res.writeHead(200,{"Content-Type":mime[path.extname(file)]||"text/html"});createReadStream(file).pipe(res)}catch(e){console.error(e);if(!res.headersSent)json(res,500,{error:"Server error"})}});
const port=Number(process.env.PORT||3000);server.listen(port,"0.0.0.0",()=>console.log(`VijayJha.in running at http://localhost:${port}`));
