import {mkdir,writeFile,unlink,stat} from "node:fs/promises";
import {createReadStream,existsSync} from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import {Readable} from "node:stream";
import ExcelJS from "exceljs";

const TYPES=new Set(["Car","Bike","Other"]),FUEL_TYPES=new Set(["Diesel","Petrol"]),MAX_FILE=5*1024*1024,MAX_SHEET=10*1024*1024,GENERIC_MIMES=new Set(["","application/octet-stream","binary/octet-stream"]);
const MIME=[
 {mime:"application/pdf",types:new Set(["application/pdf","application/x-pdf","application/acrobat","applications/vnd.pdf","text/pdf"]),ext:new Set(["pdf"]),magic:b=>{const header=b.subarray(0,1024).indexOf(Buffer.from("%PDF-")),eof=b.subarray(Math.max(0,b.length-4096)).indexOf(Buffer.from("%%EOF"));return header>=0&&eof>=0}},
 {mime:"image/jpeg",types:new Set(["image/jpeg","image/pjpeg"]),ext:new Set(["jpg","jpeg"]),magic:b=>b[0]===255&&b[1]===216&&b[2]===255},
 {mime:"image/png",types:new Set(["image/png","image/x-png"]),ext:new Set(["png"]),magic:b=>b.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10]))}
];
const clean=(v="",n=5000)=>(v==null?"":String(v)).replace(/[<>]/g,"").trim().slice(0,n);
const positive=(v,fallback,max=100)=>{const n=Number.parseInt(v,10);return Number.isFinite(n)&&n>0?Math.min(n,max):fallback};
const addColumn=(db,table,name,definition)=>{const cols=new Set(db.prepare(`PRAGMA table_info(${table})`).all().map(x=>x.name));if(!cols.has(name))db.exec(`ALTER TABLE ${table} ADD COLUMN ${name} ${definition}`)};
const csv=v=>`"${String(v??"").replaceAll('"','""')}"`;
const IMPORT_HEADERS=["Sno.","Vehicle Number","Car Owner Name","Vehicle Type","Fuel Type","Manufacturer","Company/Brand","Model","Variant","Purchase Date","Current KM","Chassis Number","Engine Number","First Party Insurance Company","First Party Policy No.","First Party Start Date","First Party Expiry Date","Third Party Insurance Company","Third Party Policy No.","Third Party Start Date","Third Party Expiry Date","PUC Number","PUC Issue Date","PUC Expiry Date","Notes","Location"];
const INSURANCE_COMPANIES=[
 ["Acko General Insurance Limited","ACKO"],
 ["Agriculture Insurance Company of India Limited","AIC"],
 ["Bajaj Allianz General Insurance Company Limited","Bajaj Allianz"],
 ["Cholamandalam MS General Insurance Company Limited","Chola MS"],
 ["ECGC Limited","ECGC"],
 ["Future Generali India Insurance Company Limited","Future Generali"],
 ["Go Digit General Insurance Limited","Digit"],
 ["HDFC ERGO General Insurance Company Limited","HDFC ERGO"],
 ["ICICI Lombard General Insurance Company Limited","ICICI Lombard"],
 ["IFFCO Tokio General Insurance Company Limited","IFFCO Tokio"],
 ["Zurich Kotak General Insurance Company (India) Limited","Zurich Kotak"],
 ["Kshema General Insurance Limited","Kshema"],
 ["Liberty General Insurance Limited","Liberty"],
 ["Magma General Insurance Limited","Magma"],
 ["National Insurance Company Limited","National Insurance"],
 ["Navi General Insurance Limited","Navi"],
 ["Raheja QBE General Insurance Company Limited","Raheja QBE"],
 ["Reliance General Insurance Company Limited","Reliance General"],
 ["Royal Sundaram General Insurance Company Limited","Royal Sundaram"],
 ["SBI General Insurance Company Limited","SBI General"],
 ["Shriram General Insurance Company Limited","Shriram General"],
 ["Tata AIG General Insurance Company Limited","Tata AIG"],
 ["The New India Assurance Company Limited","New India Assurance"],
 ["The Oriental Insurance Company Limited","Oriental Insurance"],
 ["United India Insurance Company Limited","United India"],
 ["Universal Sompo General Insurance Company Limited","Universal Sompo"],
 ["Zuno General Insurance Limited","Zuno"]
];
const INSURANCE_ALIASES=[
 ["ICICI Lombard General Insurance Company Limited","Bharti AXA General Insurance Company Limited"],
 ["ICICI Lombard General Insurance Company Limited","Bharti AXA General Insurance"],
 ["Zurich Kotak General Insurance Company (India) Limited","Kotak Mahindra General Insurance Company Limited"],
 ["Zurich Kotak General Insurance Company (India) Limited","Kotak General Insurance"],
 ["Magma General Insurance Limited","Magma HDI General Insurance Company Limited"],
 ["Zuno General Insurance Limited","Edelweiss General Insurance Company Limited"]
];

export async function createVehicleApi({db,root,authed,currentUser,ownerUserId,json,sharing}){
 const store=path.join(root,"data","private-vehicle-documents");await mkdir(store,{recursive:true});
 db.exec("CREATE TABLE IF NOT EXISTS vehicle_locations(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,name TEXT NOT NULL COLLATE NOCASE,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP,UNIQUE(user_id,name))");
 db.exec(`CREATE TABLE IF NOT EXISTS insurance_companies(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL COLLATE NOCASE UNIQUE,short_name TEXT NOT NULL DEFAULT '',logo TEXT DEFAULT '',website TEXT DEFAULT '',active INTEGER NOT NULL DEFAULT 1 CHECK(active IN (0,1)),sort_name TEXT NOT NULL DEFAULT '',created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP); CREATE TABLE IF NOT EXISTS insurance_company_aliases(id INTEGER PRIMARY KEY AUTOINCREMENT,company_id INTEGER NOT NULL REFERENCES insurance_companies(id) ON DELETE CASCADE,alias TEXT NOT NULL COLLATE NOCASE UNIQUE,created_at TEXT DEFAULT CURRENT_TIMESTAMP); CREATE INDEX IF NOT EXISTS idx_insurance_companies_active_sort ON insurance_companies(active,sort_name COLLATE NOCASE,name COLLATE NOCASE); CREATE INDEX IF NOT EXISTS idx_insurance_aliases_company ON insurance_company_aliases(company_id);`);
 const insertCompany=db.prepare("INSERT OR IGNORE INTO insurance_companies(name,short_name,sort_name) VALUES(?,?,?)");
 const insertAlias=db.prepare("INSERT OR IGNORE INTO insurance_company_aliases(company_id,alias) SELECT id,? FROM insurance_companies WHERE name=? COLLATE NOCASE");
 db.exec("BEGIN");try{for(const[name,shortName]of INSURANCE_COMPANIES)insertCompany.run(name,shortName,name.replace(/^The\s+/i,""));for(const[name,alias]of INSURANCE_ALIASES)insertAlias.run(alias,name);db.exec("COMMIT")}catch(error){db.exec("ROLLBACK");throw error}
 db.exec(`PRAGMA foreign_keys=ON; CREATE TABLE IF NOT EXISTS vehicles(id INTEGER PRIMARY KEY AUTOINCREMENT,vehicle_number TEXT NOT NULL COLLATE NOCASE,type TEXT NOT NULL CHECK(type IN ('Car','Bike','Other')),make TEXT NOT NULL,model TEXT NOT NULL,variant TEXT DEFAULT '',purchase_date TEXT DEFAULT '',current_km INTEGER,photo TEXT DEFAULT '',notes TEXT DEFAULT '',created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP); CREATE TABLE IF NOT EXISTS vehicle_documents(id INTEGER PRIMARY KEY AUTOINCREMENT,vehicle_id INTEGER NOT NULL REFERENCES vehicles(id) ON DELETE CASCADE,name TEXT NOT NULL,category TEXT NOT NULL,document_number TEXT DEFAULT '',issue_date TEXT DEFAULT '',expiry_date TEXT,notes TEXT DEFAULT '',deleted_at TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP); CREATE TABLE IF NOT EXISTS document_versions(id INTEGER PRIMARY KEY AUTOINCREMENT,document_id INTEGER NOT NULL REFERENCES vehicle_documents(id) ON DELETE CASCADE,stored_name TEXT NOT NULL UNIQUE,original_name TEXT NOT NULL,mime_type TEXT NOT NULL,file_size INTEGER NOT NULL,is_active INTEGER NOT NULL DEFAULT 1,deleted_at TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP); CREATE TABLE IF NOT EXISTS notification_deliveries(id INTEGER PRIMARY KEY AUTOINCREMENT,document_id INTEGER NOT NULL REFERENCES vehicle_documents(id) ON DELETE CASCADE,reminder_days INTEGER NOT NULL,delivery_date TEXT NOT NULL,status TEXT NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP,UNIQUE(document_id,reminder_days,delivery_date)); CREATE TABLE IF NOT EXISTS vehicle_audit_log(id INTEGER PRIMARY KEY AUTOINCREMENT,action TEXT NOT NULL,vehicle_id INTEGER,document_id INTEGER,created_at TEXT DEFAULT CURRENT_TIMESTAMP);`);
 for(const t of["vehicles","vehicle_documents","notification_deliveries","vehicle_audit_log"])addColumn(db,t,"user_id","INTEGER REFERENCES users(id)");
 const optionalColumns={vehicle_name:"TEXT",fuel_type:"TEXT",manufacturer:"TEXT",brand:"TEXT",location_id:"INTEGER REFERENCES vehicle_locations(id) ON DELETE SET NULL",registration_status:"TEXT DEFAULT 'Permanent'",temporary_registration_expiry:"TEXT",chassis_number:"TEXT",engine_number:"TEXT",first_party_insurer:"TEXT",first_party_insurance_company_id:"INTEGER REFERENCES insurance_companies(id) ON DELETE SET NULL",first_party_policy_number:"TEXT",first_party_start_date:"TEXT",first_party_expiry_date:"TEXT",third_party_insurer:"TEXT",third_party_insurance_company_id:"INTEGER REFERENCES insurance_companies(id) ON DELETE SET NULL",third_party_policy_number:"TEXT",third_party_start_date:"TEXT",third_party_expiry_date:"TEXT",puc_number:"TEXT",puc_issue_date:"TEXT",puc_expiry_date:"TEXT"};for(const[name,definition]of Object.entries(optionalColumns))addColumn(db,"vehicles",name,definition);db.exec("UPDATE vehicles SET registration_status='Permanent' WHERE registration_status IS NULL OR registration_status=''");
 if(ownerUserId){for(const t of["vehicles","vehicle_documents","notification_deliveries","vehicle_audit_log"])db.prepare(`UPDATE ${t} SET user_id=? WHERE user_id IS NULL`).run(ownerUserId)}
 const oldInfo=db.prepare("PRAGMA table_info(vehicles)").all(),requiresOptionalRebuild=oldInfo.some(x=>["type","make","model"].includes(x.name)&&x.notnull)||db.prepare("PRAGMA index_list(vehicles)").all().some(x=>x.origin==="u"&&x.unique);if(requiresOptionalRebuild){db.exec(`PRAGMA foreign_keys=OFF; BEGIN; CREATE TABLE vehicles_optional(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER REFERENCES users(id),vehicle_number TEXT NOT NULL COLLATE NOCASE,vehicle_name TEXT,type TEXT,manufacturer TEXT,brand TEXT,make TEXT,model TEXT,variant TEXT,purchase_date TEXT,current_km INTEGER,chassis_number TEXT,engine_number TEXT,photo TEXT,notes TEXT,first_party_insurer TEXT,first_party_insurance_company_id INTEGER REFERENCES insurance_companies(id) ON DELETE SET NULL,first_party_policy_number TEXT,first_party_start_date TEXT,first_party_expiry_date TEXT,third_party_insurer TEXT,third_party_insurance_company_id INTEGER REFERENCES insurance_companies(id) ON DELETE SET NULL,third_party_policy_number TEXT,third_party_start_date TEXT,third_party_expiry_date TEXT,puc_number TEXT,puc_issue_date TEXT,puc_expiry_date TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP); INSERT INTO vehicles_optional SELECT id,user_id,vehicle_number,vehicle_name,NULLIF(type,''),manufacturer,COALESCE(NULLIF(brand,''),make),make,model,variant,purchase_date,current_km,chassis_number,engine_number,photo,notes,first_party_insurer,first_party_insurance_company_id,first_party_policy_number,first_party_start_date,first_party_expiry_date,third_party_insurer,third_party_insurance_company_id,third_party_policy_number,third_party_start_date,third_party_expiry_date,puc_number,puc_issue_date,puc_expiry_date,created_at,updated_at FROM vehicles; DROP TABLE vehicles; ALTER TABLE vehicles_optional RENAME TO vehicles; COMMIT; PRAGMA foreign_keys=ON`)}else db.exec("UPDATE vehicles SET brand=COALESCE(NULLIF(brand,''),make) WHERE brand IS NULL OR brand=''");
 db.exec(`DROP INDEX IF EXISTS idx_vehicles_number; CREATE UNIQUE INDEX IF NOT EXISTS idx_vehicles_user_number ON vehicles(user_id,vehicle_number); CREATE INDEX IF NOT EXISTS idx_vehicles_user_type ON vehicles(user_id,type); CREATE INDEX IF NOT EXISTS idx_vehicles_user_make_model ON vehicles(user_id,make,model); CREATE INDEX IF NOT EXISTS idx_documents_user_vehicle ON vehicle_documents(user_id,vehicle_id,deleted_at); CREATE INDEX IF NOT EXISTS idx_documents_user_expiry ON vehicle_documents(user_id,expiry_date,deleted_at); CREATE INDEX IF NOT EXISTS idx_versions_document ON document_versions(document_id,is_active,deleted_at); CREATE INDEX IF NOT EXISTS idx_audit_user_created ON vehicle_audit_log(user_id,created_at DESC);`);
 for(const[name,definition]of Object.entries(optionalColumns))addColumn(db,"vehicles",name,definition);db.exec("UPDATE vehicles SET registration_status='Permanent' WHERE registration_status IS NULL OR registration_status=''");
 for(const prefix of["first_party","third_party"]){db.exec(`UPDATE vehicles SET ${prefix}_insurance_company_id=(SELECT c.id FROM insurance_companies c WHERE c.name=TRIM(vehicles.${prefix}_insurer) COLLATE NOCASE OR c.short_name=TRIM(vehicles.${prefix}_insurer) COLLATE NOCASE LIMIT 1) WHERE ${prefix}_insurance_company_id IS NULL AND NULLIF(TRIM(${prefix}_insurer),'') IS NOT NULL; UPDATE vehicles SET ${prefix}_insurance_company_id=(SELECT a.company_id FROM insurance_company_aliases a WHERE a.alias=TRIM(vehicles.${prefix}_insurer) COLLATE NOCASE LIMIT 1) WHERE ${prefix}_insurance_company_id IS NULL AND NULLIF(TRIM(${prefix}_insurer),'') IS NOT NULL;`)}
 const audit=(uid,action,vehicleId=null,documentId=null)=>db.prepare("INSERT INTO vehicle_audit_log(user_id,action,vehicle_id,document_id) VALUES(?,?,?,?)").run(uid,action,vehicleId,documentId);
 const vehicle=(uid,id)=>sharing.access(uid,id);
 const canEdit=(uid,id)=>["owner","editor"].includes(vehicle(uid,id)?.access_level);
 const isOwner=(uid,id)=>vehicle(uid,id)?.access_level==="owner";
 const location=(uid,id)=>id?db.prepare("SELECT * FROM vehicle_locations WHERE id=? AND user_id=?").get(id,uid):null;
 const document=(uid,vid,did)=>vehicle(uid,vid)&&db.prepare("SELECT d.* FROM vehicle_documents d WHERE d.id=? AND d.vehicle_id=? AND d.deleted_at IS NULL").get(did,vid);
 const body=async req=>{const chunks=[];for await(const c of req)chunks.push(c);return JSON.parse(Buffer.concat(chunks).toString()||"{}")};
 const form=async req=>new Request(`http://localhost${req.url}`,{method:req.method,headers:req.headers,body:Readable.toWeb(req),duplex:"half"}).formData();
 const resolveInsurance=(idValue,nameValue)=>{const rawName=clean(nameValue,160),name=rawName.toLowerCase()==="null"?"":rawName,id=idValue===""||idValue==null?null:Number(idValue);if(id!==null){if(!Number.isSafeInteger(id)||id<=0)throw new Error("Invalid insurance company");const company=db.prepare("SELECT id,name FROM insurance_companies WHERE id=?").get(id);if(!company)throw new Error("Invalid insurance company");return{id:Number(company.id),name:company.name}}if(!name)return{id:null,name:""};const company=db.prepare("SELECT id,name FROM insurance_companies WHERE name=? COLLATE NOCASE OR short_name=? COLLATE NOCASE UNION SELECT c.id,c.name FROM insurance_company_aliases a JOIN insurance_companies c ON c.id=a.company_id WHERE a.alias=? COLLATE NOCASE LIMIT 1").get(name,name,name);return company?{id:Number(company.id),name:company.name}:{id:null,name}};
 const input=b=>{const type=clean(b.type,10),fuelType=clean(b.fuel_type,10),registrationStatus=clean(b.registration_status,12)||"Permanent",locationId=b.location_id===""||b.location_id==null?null:Number(b.location_id),fp=resolveInsurance(b.first_party_insurance_company_id,b.first_party_insurer),tp=resolveInsurance(b.third_party_insurance_company_id,b.third_party_insurer),x={number:clean(b.vehicle_number,40).toUpperCase(),name:clean(b.vehicle_name,120),type:type||null,fuelType:fuelType||null,locationId:Number.isSafeInteger(locationId)&&locationId>0?locationId:null,registrationStatus,temporaryExpiry:registrationStatus==="Temporary"?clean(b.temporary_registration_expiry,10):"",manufacturer:clean(b.manufacturer,120),brand:clean(b.brand??b.make,120),model:clean(b.model,120),variant:clean(b.variant,120),purchase:clean(b.purchase_date,10),km:b.current_km===""||b.current_km==null?null:Number(b.current_km),chassisNumber:clean(b.chassis_number,120),engineNumber:clean(b.engine_number,120),photo:clean(b.photo,500),notes:clean(b.notes),fpInsurer:fp.name,fpCompanyId:fp.id,fpPolicy:clean(b.first_party_policy_number,120),fpStart:clean(b.first_party_start_date,10),fpExpiry:clean(b.first_party_expiry_date,10),tpInsurer:tp.name,tpCompanyId:tp.id,tpPolicy:clean(b.third_party_policy_number,120),tpStart:clean(b.third_party_start_date,10),tpExpiry:clean(b.third_party_expiry_date,10),pucNumber:clean(b.puc_number,120),pucIssue:clean(b.puc_issue_date,10),pucExpiry:clean(b.puc_expiry_date,10)};if(!x.number)throw new Error("Vehicle number is required");if(x.type&&!TYPES.has(x.type))throw new Error("Vehicle type must be Car, Bike, Other or blank");if(x.fuelType&&!FUEL_TYPES.has(x.fuelType))throw new Error("Fuel type must be Diesel, Petrol or blank");if(!["Permanent","Temporary"].includes(x.registrationStatus))throw new Error("Registration status must be Permanent or Temporary");if(x.km!==null&&(!Number.isSafeInteger(x.km)||x.km<0))throw new Error("Current KM must be a positive whole number");return x};
 const payload=x=>({vehicle_number:x.number,vehicle_name:x.name,type:x.type||"",fuel_type:x.fuelType||"",registration_status:x.registrationStatus,temporary_registration_expiry:x.temporaryExpiry,manufacturer:x.manufacturer,brand:x.brand,model:x.model,variant:x.variant,purchase_date:x.purchase,current_km:x.km,chassis_number:x.chassisNumber,engine_number:x.engineNumber,notes:x.notes,first_party_insurer:x.fpInsurer,first_party_insurance_company_id:x.fpCompanyId,first_party_policy_number:x.fpPolicy,first_party_start_date:x.fpStart,first_party_expiry_date:x.fpExpiry,third_party_insurer:x.tpInsurer,third_party_insurance_company_id:x.tpCompanyId,third_party_policy_number:x.tpPolicy,third_party_start_date:x.tpStart,third_party_expiry_date:x.tpExpiry,puc_number:x.pucNumber,puc_issue_date:x.pucIssue,puc_expiry_date:x.pucExpiry});
 const mutableFields="vehicle_name,type,fuel_type,location_id,registration_status,temporary_registration_expiry,manufacturer,brand,make,model,variant,purchase_date,current_km,chassis_number,engine_number,photo,notes,first_party_insurer,first_party_insurance_company_id,first_party_policy_number,first_party_start_date,first_party_expiry_date,third_party_insurer,third_party_insurance_company_id,third_party_policy_number,third_party_start_date,third_party_expiry_date,puc_number,puc_issue_date,puc_expiry_date";
 const values=x=>[x.name,x.type,x.fuelType,x.locationId,x.registrationStatus,x.temporaryExpiry,x.manufacturer,x.brand,x.brand,x.model,x.variant,x.purchase,x.km,x.chassisNumber,x.engineNumber,x.photo,x.notes,x.fpInsurer,x.fpCompanyId,x.fpPolicy,x.fpStart,x.fpExpiry,x.tpInsurer,x.tpCompanyId,x.tpPolicy,x.tpStart,x.tpExpiry,x.pucNumber,x.pucIssue,x.pucExpiry];
 const importFields="vehicle_name,type,fuel_type,manufacturer,brand,make,model,variant,purchase_date,current_km,chassis_number,engine_number,notes,first_party_insurer,first_party_insurance_company_id,first_party_policy_number,first_party_start_date,first_party_expiry_date,third_party_insurer,third_party_insurance_company_id,third_party_policy_number,third_party_start_date,third_party_expiry_date,puc_number,puc_issue_date,puc_expiry_date".split(","),importValues=x=>[x.name,x.type,x.fuelType,x.manufacturer,x.brand,x.brand,x.model,x.variant,x.purchase,x.km,x.chassisNumber,x.engineNumber,x.notes,x.fpInsurer,x.fpCompanyId,x.fpPolicy,x.fpStart,x.fpExpiry,x.tpInsurer,x.tpCompanyId,x.tpPolicy,x.tpStart,x.tpExpiry,x.pucNumber,x.pucIssue,x.pucExpiry];
 const indiaDate=()=>{const p=Object.fromEntries(new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Kolkata",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date()).filter(x=>x.type!=="literal").map(x=>[x.type,x.value]));return`${p.year}-${p.month}-${p.day}`},expiryStatus=expiry=>{if(!expiry)return"No Expiry";const days=Math.round((Date.parse(`${expiry}T00:00:00Z`)-Date.parse(`${indiaDate()}T00:00:00Z`))/864e5);return days<0?"Expired":days<=10?"Expiring Soon":"Valid"},overallStatus=records=>{const statuses=records.filter(x=>x.exists).map(x=>expiryStatus(x.expiry));for(const s of["Expired","Expiring Soon","Valid","No Expiry"])if(statuses.includes(s))return s;return"No Documents"};
  const checkedFile=async file=>{if(!file||typeof file==="string"||!file.size)throw new Error("Document file is required");if(file.size>MAX_FILE)throw new Error("File is too large. Maximum allowed size is 5 MB.");const original=path.basename(String(file.name||"document").replaceAll("\\","/")).slice(0,255),ext=path.extname(original).slice(1).toLowerCase(),declared=String(file.type||"").split(";",1)[0].trim().toLowerCase(),rule=MIME.find(candidate=>candidate.ext.has(ext)),bytes=Buffer.from(await file.arrayBuffer()),mimeAllowed=rule&&(GENERIC_MIMES.has(declared)||rule.types.has(declared));if(!rule||!mimeAllowed||!rule.magic(bytes))throw new Error("File must be PDF, JPG, JPEG or PNG and maximum 5 MB.");return{original,ext,mime:rule.mime,bytes,size:file.size,stored:`${crypto.randomUUID()}.${ext}`}};
 const csvRows=text=>{const rows=[];let row=[],cell="",quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++}else quoted=!quoted}else if(c===","&&!quoted){row.push(cell);cell=""}else if((c==="\n"||c==="\r")&&!quoted){if(c==="\r"&&text[i+1]==="\n")i++;row.push(cell);if(row.some(x=>x!==""))rows.push(row);row=[];cell=""}else cell+=c}row.push(cell);if(row.some(x=>x!==""))rows.push(row);return rows};
 const sheetRows=async(buffer,ext)=>{let matrix=[];if(ext===".csv")matrix=csvRows(buffer.toString("utf8").replace(/^\ufeff/,""));else{const wb=new ExcelJS.Workbook();await wb.xlsx.load(buffer);const ws=wb.worksheets[0];if(!ws)throw new Error("Workbook has no worksheet");ws.eachRow({includeEmpty:false},r=>matrix.push(r.values.slice(1).map(v=>v instanceof Date?v.toISOString().slice(0,10):String(v??""))))}const headers=(matrix.shift()||[]).map(String);return matrix.map((rowValues,i)=>{const r=Object.fromEntries(headers.map((h,n)=>[h,rowValues[n]??""])),get=(...ks)=>{for(const k of ks)if(r[k]!==undefined)return r[k];return""},raw={vehicle_number:get("Vehicle Number","vehicle_number"),vehicle_name:get("Car Owner Name","Vehicle Name","vehicle_name"),type:get("Vehicle Type","type"),fuel_type:get("Fuel Type","fuel_type"),manufacturer:get("Manufacturer","manufacturer"),brand:get("Company/Brand","Brand","brand"),model:get("Model","model"),variant:get("Variant","variant"),purchase_date:get("Purchase Date","purchase_date"),current_km:get("Current KM","current_km"),chassis_number:get("Chassis Number","chassis_number"),engine_number:get("Engine Number","engine_number"),first_party_insurer:get("First Party Insurance Company","first_party_insurer"),first_party_policy_number:get("First Party Policy No.","First Party Policy No","first_party_policy_number"),first_party_start_date:get("First Party Start Date","first_party_start_date"),first_party_expiry_date:get("First Party Expiry Date","first_party_expiry_date"),third_party_insurer:get("Third Party Insurance Company","third_party_insurer"),third_party_policy_number:get("Third Party Policy No.","Third Party Policy No","third_party_policy_number"),third_party_start_date:get("Third Party Start Date","third_party_start_date"),third_party_expiry_date:get("Third Party Expiry Date","third_party_expiry_date"),puc_number:get("PUC Number","puc_number"),puc_issue_date:get("PUC Issue Date","puc_issue_date"),puc_expiry_date:get("PUC Expiry Date","puc_expiry_date"),notes:get("Notes","notes")};try{return{row:i+2,valid:true,data:payload(input(raw))}}catch(e){return{row:i+2,valid:false,error:e.message,data:raw}}})};
 const sheetLocations=async(buffer,ext)=>{let matrix=[];if(ext===".csv")matrix=csvRows(buffer.toString("utf8").replace(/^\ufeff/,""));else{const wb=new ExcelJS.Workbook();await wb.xlsx.load(buffer);wb.worksheets[0]?.eachRow({includeEmpty:false},r=>matrix.push(r.values.slice(1).map(v=>String(v??""))))}const headers=(matrix.shift()||[]).map(String),index=headers.indexOf("Location");return matrix.map(row=>index<0?"":clean(row[index],80))};
 const allowedIds=uid=>sharing.ids(uid);
 const idFilter=ids=>ids.length?{sql:`v.id IN (${ids.map(()=>"?").join(",")})`,args:ids}:{sql:"0",args:[]};
 const listResult=(uid,url)=>{const ids=allowedIds(uid),base=idFilter(ids),page=positive(url.searchParams.get("page"),1,1e9),pageSize=positive(url.searchParams.get("pageSize"),20,100),q=clean(url.searchParams.get("q"),100),type=clean(url.searchParams.get("type"),10),locationFilter=clean(url.searchParams.get("location"),20),where=[base.sql],args=[...base.args];if(q){where.push("(v.vehicle_number LIKE ? ESCAPE '\\' OR v.vehicle_name LIKE ? ESCAPE '\\' OR v.manufacturer LIKE ? ESCAPE '\\' OR v.brand LIKE ? ESCAPE '\\' OR v.model LIKE ? ESCAPE '\\' OR v.chassis_number LIKE ? ESCAPE '\\' OR v.engine_number LIKE ? ESCAPE '\\')");const like=`%${q.replace(/[\\%_]/g,"\\$&")}%`;args.push(like,like,like,like,like,like,like)}if(TYPES.has(type)){where.push("v.type=?");args.push(type)}if(locationFilter==="unassigned")where.push("v.location_id IS NULL");else if(Number(locationFilter)>0){where.push("v.location_id=?");args.push(Number(locationFilter))}const sql=where.join(" AND "),total=Number(db.prepare(`SELECT COUNT(*) n FROM vehicles v WHERE ${sql}`).get(...args).n),items=db.prepare(`SELECT v.*,l.name location_name,(SELECT COUNT(*) FROM vehicle_documents d WHERE d.vehicle_id=v.id AND d.user_id=v.user_id AND d.deleted_at IS NULL) document_count FROM vehicles v LEFT JOIN vehicle_locations l ON l.id=v.location_id AND l.user_id=v.user_id WHERE ${sql} ORDER BY v.updated_at DESC,v.id DESC LIMIT ? OFFSET ?`).all(...args,pageSize,(page-1)*pageSize);for(const v of items){v.access_level=vehicle(uid,v.id)?.access_level||"none";const records=db.prepare("SELECT category,expiry_date FROM vehicle_documents WHERE vehicle_id=? AND user_id=? AND deleted_at IS NULL").all(v.id,v.user_id).map(x=>({exists:true,expiry:x.expiry_date}));records.push({exists:!!(v.first_party_insurer||v.first_party_policy_number||v.first_party_expiry_date),expiry:v.first_party_expiry_date},{exists:!!(v.third_party_insurer||v.third_party_policy_number||v.third_party_expiry_date),expiry:v.third_party_expiry_date},{exists:!!(v.puc_number||v.puc_expiry_date),expiry:v.puc_expiry_date});v.document_status=overallStatus(records)}return{items,page,pageSize,total,totalPages:Math.ceil(total/pageSize)}};
 const completionRecords=uid=>{const ids=allowedIds(uid);if(!ids.length)return[];const marks=ids.map(()=>"?").join(","),documents=db.prepare(`SELECT vehicle_id,category FROM vehicle_documents WHERE deleted_at IS NULL AND vehicle_id IN (${marks})`).all(...ids),categories=new Map;for(const document of documents){if(!categories.has(document.vehicle_id))categories.set(document.vehicle_id,new Set);categories.get(document.vehicle_id).add(String(document.category||"").trim().toLowerCase())}const required=[["vehicle_name","Car Owner Name"],["type","Vehicle Type"],["fuel_type","Fuel Type"],["location_id","Vehicle Location"],["registration_status","Registration Status"],["manufacturer","Manufacturer"],["brand","Company / Brand"],["model","Model"],["variant","Variant"],["purchase_date","Purchase Date"],["chassis_number","Chassis Number"],["engine_number","Engine Number"],["first_party_insurer","First Party Insurance Company"],["first_party_policy_number","First Party Policy Number"],["first_party_start_date","First Party Issue Date"],["first_party_expiry_date","First Party Expiry Date"],["third_party_insurer","Third Party Insurance Company"],["third_party_policy_number","Third Party Policy Number"],["third_party_start_date","Third Party Issue Date"],["third_party_expiry_date","Third Party Expiry Date"],["puc_number","PUC Number"],["puc_issue_date","PUC Issue Date"],["puc_expiry_date","PUC Expiry Date"]];return db.prepare(`SELECT * FROM vehicles WHERE id IN (${marks}) ORDER BY updated_at DESC,id DESC`).all(...ids).map(vehicle=>{const missing=required.filter(([field])=>vehicle[field]===null||vehicle[field]===undefined||String(vehicle[field]).trim()==="").map(([,label])=>label);if(vehicle.registration_status==="Temporary"&&!vehicle.temporary_registration_expiry)missing.push("Temporary Registration Expiry");const uploaded=categories.get(vehicle.id)||new Set,has=matcher=>[...uploaded].some(matcher);if(!has(category=>category==="first party / own damage insurance"||category.includes("first party")||category.includes("own damage")))missing.push("First Party Insurance Document");if(!has(category=>category==="rc"||category.includes("registration certificate")))missing.push("RC Document");if(!has(category=>category==="puc"||category.includes("pollution")))missing.push("PUC Document");return{id:vehicle.id,vehicle_number:vehicle.vehicle_number,vehicle_name:vehicle.vehicle_name,type:vehicle.type,missing,missing_count:missing.length}}).filter(vehicle=>vehicle.missing_count>0)};
 const dashboardResult=(uid,user)=>{const ids=allowedIds(uid),base=idFilter(ids),meta=db.prepare(`SELECT v.* FROM vehicles v WHERE ${base.sql}`).all(...base.args),metaByVehicle=new Map(meta.map(v=>[v.id,v])),docs=ids.length?db.prepare(`SELECT d.vehicle_id,d.category,d.expiry_date FROM vehicle_documents d WHERE d.deleted_at IS NULL AND d.vehicle_id IN (${ids.map(()=>"?").join(",")})`).all(...ids).filter(d=>metaByVehicle.has(d.vehicle_id)).map(x=>({exists:true,expiry:x.expiry_date})):[];for(const v of meta){if(v.first_party_insurer||v.first_party_policy_number||v.first_party_expiry_date)docs.push({exists:true,expiry:v.first_party_expiry_date});if(v.third_party_insurer||v.third_party_policy_number||v.third_party_expiry_date)docs.push({exists:true,expiry:v.third_party_expiry_date});if(v.puc_number||v.puc_expiry_date)docs.push({exists:true,expiry:v.puc_expiry_date})}const counts={expiredDocuments:0,expiringDocuments:0,validDocuments:0,noExpiryDocuments:0};for(const d of docs){const s=expiryStatus(d.expiry);if(s==="Expired")counts.expiredDocuments++;else if(s==="Expiring Soon")counts.expiringDocuments++;else if(s==="Valid")counts.validDocuments++;else counts.noExpiryDocuments++}const storage=ids.length?db.prepare(`SELECT COALESCE(SUM(x.file_size),0) bytes,COUNT(*) documents FROM document_versions x JOIN vehicle_documents d ON d.id=x.document_id WHERE d.deleted_at IS NULL AND x.is_active=1 AND x.deleted_at IS NULL AND d.vehicle_id IN (${ids.map(()=>"?").join(",")})`).get(...ids):{bytes:0,documents:0};return{totalVehicles:ids.length,incompleteVehicles:completionRecords(uid).length,...counts,...storage,user}};
 const documentsResult=(uid,url)=>{const ids=allowedIds(uid),page=positive(url.searchParams.get("page"),1,1e9),pageSize=positive(url.searchParams.get("pageSize"),20,100),requestedStatus=clean(url.searchParams.get("status"),20),statusFilter=new Set(["Valid","No Expiry"]).has(requestedStatus)?requestedStatus:"";if(!ids.length)return{items:[],page,pageSize,total:0,totalPages:0};const marks=ids.map(()=>"?").join(","),uploaded=db.prepare(`SELECT d.id,d.vehicle_id,d.name,d.category,d.document_number,d.issue_date,d.expiry_date,d.created_at,v.vehicle_number,x.original_name,x.file_size,x.mime_type FROM vehicle_documents d JOIN vehicles v ON v.id=d.vehicle_id LEFT JOIN document_versions x ON x.document_id=d.id AND x.is_active=1 AND x.deleted_at IS NULL WHERE d.deleted_at IS NULL AND d.vehicle_id IN (${marks}) ORDER BY d.updated_at DESC,d.id DESC`).all(...ids).map(item=>({...item,status:expiryStatus(item.expiry_date),source:"Uploaded document"}));let records=uploaded;if(statusFilter){const profile=[];for(const v of db.prepare(`SELECT id,vehicle_number,first_party_insurer,first_party_policy_number,first_party_start_date,first_party_expiry_date,third_party_insurer,third_party_policy_number,third_party_start_date,third_party_expiry_date,puc_number,puc_issue_date,puc_expiry_date FROM vehicles WHERE id IN (${marks})`).all(...ids)){if(v.first_party_insurer||v.first_party_policy_number||v.first_party_expiry_date)profile.push({vehicle_id:v.id,vehicle_number:v.vehicle_number,name:"First Party / Own Damage",category:"Vehicle profile",document_number:v.first_party_policy_number,issue_date:v.first_party_start_date,expiry_date:v.first_party_expiry_date,source:"Vehicle profile"});if(v.third_party_insurer||v.third_party_policy_number||v.third_party_expiry_date)profile.push({vehicle_id:v.id,vehicle_number:v.vehicle_number,name:"Third Party Insurance",category:"Vehicle profile",document_number:v.third_party_policy_number,issue_date:v.third_party_start_date,expiry_date:v.third_party_expiry_date,source:"Vehicle profile"});if(v.puc_number||v.puc_expiry_date)profile.push({vehicle_id:v.id,vehicle_number:v.vehicle_number,name:"PUC",category:"Vehicle profile",document_number:v.puc_number,issue_date:v.puc_issue_date,expiry_date:v.puc_expiry_date,source:"Vehicle profile"})}records=[...uploaded,...profile.map(item=>({...item,status:expiryStatus(item.expiry_date)}))].filter(item=>item.status===statusFilter)}const total=records.length;return{items:records.slice((page-1)*pageSize,page*pageSize),page,pageSize,total,totalPages:Math.ceil(total/pageSize),status:statusFilter||null}};
 const remindersResult=(uid,url)=>{const ids=allowedIds(uid),page=positive(url.searchParams.get("page"),1,1e9),pageSize=positive(url.searchParams.get("pageSize"),20,100);if(!ids.length)return{items:[],page,pageSize,total:0,totalPages:0};const marks=ids.map(()=>"?").join(","),vehicles=db.prepare(`SELECT id,vehicle_number,registration_status,temporary_registration_expiry,first_party_insurer,first_party_policy_number,first_party_expiry_date,third_party_insurer,third_party_policy_number,third_party_expiry_date,puc_number,puc_expiry_date FROM vehicles WHERE id IN (${marks})`).all(...ids),items=[];for(const v of vehicles){if(v.registration_status==="Temporary"&&v.temporary_registration_expiry)items.push({vehicle_id:v.id,vehicle_number:v.vehicle_number,name:"Temporary Registration",category:"Registration",expiry_date:v.temporary_registration_expiry});if(v.first_party_expiry_date)items.push({vehicle_id:v.id,vehicle_number:v.vehicle_number,name:"First Party / Own Damage",category:"Insurance",expiry_date:v.first_party_expiry_date});if(v.third_party_expiry_date)items.push({vehicle_id:v.id,vehicle_number:v.vehicle_number,name:"Third Party Insurance",category:"Insurance",expiry_date:v.third_party_expiry_date});if(v.puc_expiry_date)items.push({vehicle_id:v.id,vehicle_number:v.vehicle_number,name:"PUC",category:"PUC",expiry_date:v.puc_expiry_date})}items.push(...db.prepare(`SELECT d.vehicle_id,v.vehicle_number,d.name,d.category,d.expiry_date FROM vehicle_documents d JOIN vehicles v ON v.id=d.vehicle_id WHERE d.deleted_at IS NULL AND d.expiry_date IS NOT NULL AND d.expiry_date<>'' AND d.vehicle_id IN (${marks})`).all(...ids));const reminders=items.map(item=>({...item,status:expiryStatus(item.expiry_date)})).filter(item=>item.status==="Expired"||item.status==="Expiring Soon").sort((a,b)=>String(a.expiry_date).localeCompare(String(b.expiry_date))||String(a.vehicle_number).localeCompare(String(b.vehicle_number))),total=reminders.length;return{items:reminders.slice((page-1)*pageSize,page*pageSize),page,pageSize,total,totalPages:Math.ceil(total/pageSize)}};
 const incompleteResult=(uid,url)=>{const page=positive(url.searchParams.get("page"),1,1e9),pageSize=positive(url.searchParams.get("pageSize"),20,100),records=completionRecords(uid),total=records.length;return{items:records.slice((page-1)*pageSize,page*pageSize),page,pageSize,total,totalPages:Math.ceil(total/pageSize)}};
 const locationsResult=uid=>{const ids=allowedIds(uid),base=idFilter(ids),locations=db.prepare(`SELECT l.id,l.name,COUNT(v.id) vehicle_count FROM vehicle_locations l LEFT JOIN vehicles v ON v.location_id=l.id AND ${base.sql} WHERE l.user_id=? OR EXISTS(SELECT 1 FROM location_shares s WHERE s.location_id=l.id AND s.grantee_user_id=?) GROUP BY l.id ORDER BY l.name COLLATE NOCASE`).all(...base.args,uid,uid),unassigned=ids.length?Number(db.prepare(`SELECT COUNT(*) n FROM vehicles WHERE location_id IS NULL AND id IN (${ids.map(()=>"?").join(",")})`).get(...ids).n):0,sharedAccess=db.prepare(`SELECT l.name location_name,s.permission,s.scope,CASE WHEN s.scope='selected' THEN COUNT(a.vehicle_id) ELSE COUNT(v.id) END vehicle_count FROM location_shares s JOIN vehicle_locations l ON l.id=s.location_id LEFT JOIN shared_vehicle_assignments a ON a.share_id=s.id LEFT JOIN vehicles v ON v.user_id=s.owner_user_id AND v.location_id=s.location_id WHERE s.grantee_user_id=? GROUP BY s.id ORDER BY l.name`).all(uid);return{locations,unassigned,sharedAccess}};
 return async(req,res,url)=>{
  if(!url.pathname.startsWith("/api/private/vehicles"))return false;
   if(!authed(req))return json(res,401,{error:"Login required"});const user=currentUser(req),uid=user.id,managedUser=user.account_kind==="managed";if(user.force_password_reset)return json(res,403,{error:"Change your temporary password before accessing the Vehicle Portal"});
  const sharingResponse=await sharing.api(req,res,url);if(sharingResponse!==false)return sharingResponse;
  if(!["GET","HEAD"].includes(req.method)){const origin=req.headers.origin;if(origin&&origin!==`http://${req.headers.host}`&&origin!==`https://${req.headers.host}`)return json(res,403,{error:"Invalid origin"})}
   try{
   if(url.pathname==="/api/private/vehicles/insurance-companies"&&req.method==="GET"){const q=clean(url.searchParams.get("q"),100),letter=clean(url.searchParams.get("letter"),1).toUpperCase(),where=["c.active=1"],args=[];if(q){where.push("(c.name LIKE ? ESCAPE '\\' OR c.short_name LIKE ? ESCAPE '\\' OR EXISTS(SELECT 1 FROM insurance_company_aliases a WHERE a.company_id=c.id AND a.alias LIKE ? ESCAPE '\\'))");const like=`%${q.replace(/[\\%_]/g,"\\$&")}%`;args.push(like,like,like)}if(/^[A-Z]$/.test(letter)){where.push("UPPER(SUBSTR(COALESCE(NULLIF(c.sort_name,''),c.name),1,1))=?");args.push(letter)}const items=db.prepare(`SELECT c.id,c.name,c.short_name,c.logo,c.website FROM insurance_companies c WHERE ${where.join(" AND ")} ORDER BY COALESCE(NULLIF(c.sort_name,''),c.name) COLLATE NOCASE,c.name COLLATE NOCASE`).all(...args).map(company=>({id:Number(company.id),name:company.name,shortName:company.short_name,logo:company.logo||"",website:company.website||""}));return json(res,200,{items,total:items.length})}
    if(managedUser&&(url.pathname.startsWith("/api/private/vehicles/import")||url.pathname==="/api/private/vehicles/export"||(url.pathname==="/api/private/vehicles"&&req.method==="POST")||(url.pathname.startsWith("/api/private/vehicles/locations")&&!['GET','HEAD'].includes(req.method))))return json(res,403,{error:"This action is not available for assigned-access users"});
   if(url.pathname==="/api/private/vehicles/import/preview"&&req.method==="POST"){const fd=await form(req),file=fd.get("file"),ext=file&&typeof file!=="string"?path.extname(file.name).toLowerCase():"";if(!file||typeof file==="string"||!file.size||file.size>MAX_SHEET||![".csv",".xlsx"].includes(ext))return json(res,400,{error:"A .csv or .xlsx file up to 10 MB is required"});const buffer=Buffer.from(await file.arrayBuffer()),rows=await sheetRows(buffer,ext),names=await sheetLocations(buffer,ext),owned=new Set(db.prepare("SELECT name FROM vehicle_locations WHERE user_id=?").all(uid).map(x=>x.name.toLowerCase()));rows.forEach((r,i)=>{r.data.location_name=names[i]||"";if(r.data.location_name&&!owned.has(r.data.location_name.toLowerCase())){r.missingLocation=true;r.warning=`Location '${r.data.location_name}' does not exist`}});const valid=rows.filter(r=>r.valid),numbers=valid.map(r=>r.data.vehicle_number),existing=new Set(numbers.length?db.prepare(`SELECT vehicle_number FROM vehicles WHERE user_id=? AND vehicle_number IN (${numbers.map(()=>"?").join(",")})`).all(uid,...numbers).map(r=>r.vehicle_number.toUpperCase()):[]);for(const r of valid)if(existing.has(r.data.vehicle_number)){r.duplicate=true;r.warning=r.warning||"Vehicle number already exists"}return json(res,200,{rows,valid:valid.length,invalid:rows.length-valid.length,duplicates:valid.filter(r=>r.duplicate).length,missingLocations:[...new Set(rows.filter(r=>r.missingLocation).map(r=>r.data.location_name))]})}
   if(url.pathname==="/api/private/vehicles/import/commit"&&req.method==="POST"){const b=await body(req),mode=b.duplicateMode==="update"?"update":"skip",createMissing=!!b.createMissingLocations,rows=Array.isArray(b.rows)?b.rows:[];let created=0,updated=0,skipped=0;db.exec("BEGIN");try{for(const raw of rows){let x;try{x=input(raw.data||raw)}catch{skipped++;continue}const locationName=clean((raw.data||raw).location_name,80);let locationId=null;if(locationName){let loc=db.prepare("SELECT id FROM vehicle_locations WHERE user_id=? AND name=? COLLATE NOCASE").get(uid,locationName);if(!loc&&createMissing){const made=db.prepare("INSERT INTO vehicle_locations(user_id,name) VALUES(?,?)").run(uid,locationName);loc={id:Number(made.lastInsertRowid)}}if(!loc){skipped++;continue}locationId=loc.id}const old=db.prepare("SELECT id FROM vehicles WHERE user_id=? AND vehicle_number=?").get(uid,x.number);if(old){if(mode==="skip"){skipped++;continue}db.prepare(`UPDATE vehicles SET ${importFields.map(f=>`${f}=?`).join(",")},location_id=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND user_id=?`).run(...importValues(x),locationId,old.id,uid);updated++}else{db.prepare(`INSERT INTO vehicles(user_id,vehicle_number,${importFields.join(",")},location_id) VALUES(${Array(3+importValues(x).length).fill("?").join(",")})`).run(uid,x.number,...importValues(x),locationId);created++}}db.exec("COMMIT")}catch(e){db.exec("ROLLBACK");throw e}audit(uid,"vehicles_imported");return json(res,200,{created,updated,skipped})}
   if(url.pathname==="/api/private/vehicles/export"&&req.method==="GET"){const rows=db.prepare("SELECT v.vehicle_number 'Vehicle Number',v.vehicle_name 'Car Owner Name',v.type 'Vehicle Type',v.fuel_type 'Fuel Type',v.manufacturer Manufacturer,v.brand 'Company/Brand',v.model Model,v.variant Variant,v.purchase_date 'Purchase Date',v.current_km 'Current KM',v.chassis_number 'Chassis Number',v.engine_number 'Engine Number',v.first_party_insurer 'First Party Insurance Company',v.first_party_policy_number 'First Party Policy No.',v.first_party_start_date 'First Party Start Date',v.first_party_expiry_date 'First Party Expiry Date',v.third_party_insurer 'Third Party Insurance Company',v.third_party_policy_number 'Third Party Policy No.',v.third_party_start_date 'Third Party Start Date',v.third_party_expiry_date 'Third Party Expiry Date',v.puc_number 'PUC Number',v.puc_issue_date 'PUC Issue Date',v.puc_expiry_date 'PUC Expiry Date',v.notes Notes,l.name Location,COUNT(d.id) 'Document Count' FROM vehicles v LEFT JOIN vehicle_locations l ON l.id=v.location_id AND l.user_id=v.user_id LEFT JOIN vehicle_documents d ON d.vehicle_id=v.id AND d.user_id=v.user_id AND d.deleted_at IS NULL WHERE v.user_id=? GROUP BY v.id ORDER BY v.vehicle_number").all(uid),headers=Object.keys(rows[0]||Object.fromEntries(IMPORT_HEADERS.slice(1).map(h=>[h,""])));if(url.searchParams.get("format")==="xlsx"){const wb=new ExcelJS.Workbook(),ws=wb.addWorksheet("Vehicles");ws.addRow(headers);for(const row of rows)ws.addRow(headers.map(h=>row[h]));ws.getRow(1).font={bold:true};ws.columns.forEach(c=>c.width=20);const out=Buffer.from(await wb.xlsx.writeBuffer());res.writeHead(200,{"Content-Type":"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","Content-Disposition":"attachment; filename=my-vehicles.xlsx","Cache-Control":"no-store"});return res.end(out)}const out=[headers.map(csv).join(","),...rows.map(r=>headers.map(h=>csv(r[h])).join(","))].join("\r\n");res.writeHead(200,{"Content-Type":"text/csv; charset=utf-8","Content-Disposition":"attachment; filename=my-vehicles.csv","Cache-Control":"no-store"});return res.end(`\ufeff${out}`)}
   if(url.pathname==="/api/private/vehicles"&&req.method==="GET"&&url.searchParams.has("location"))return json(res,200,listResult(uid,url))
   if(url.pathname==="/api/private/vehicles/locations"&&req.method==="GET")return json(res,200,locationsResult(uid))
   if(url.pathname==="/api/private/vehicles/locations"&&req.method==="POST"){const name=clean((await body(req)).name,80);if(!name)throw new Error("Location name is required");const r=db.prepare("INSERT INTO vehicle_locations(user_id,name) VALUES(?,?)").run(uid,name);return json(res,201,{id:Number(r.lastInsertRowid),name})}
   const locationRoute=url.pathname.match(/^\/api\/private\/vehicles\/locations\/(\d+)$/);if(locationRoute){const id=Number(locationRoute[1]),owned=location(uid,id);if(!owned)return json(res,404,{error:"Location not found"});if(req.method==="PUT"){const name=clean((await body(req)).name,80);if(!name)throw new Error("Location name is required");db.prepare("UPDATE vehicle_locations SET name=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND user_id=?").run(name,id,uid);return json(res,200,{ok:true})}if(req.method==="DELETE"){const b=await body(req),count=Number(db.prepare("SELECT COUNT(*) n FROM vehicles WHERE user_id=? AND location_id=?").get(uid,id).n);if(count&&!['unassign','move'].includes(b.action))return json(res,409,{error:`This location is assigned to ${count} vehicles. What should happen?`,vehicleCount:count,options:["move","unassign","cancel"]});if(b.action==="move"){const target=Number(b.moveToLocationId);if(target===id||!location(uid,target))return json(res,400,{error:"Choose another valid location"});db.prepare("UPDATE vehicles SET location_id=?,updated_at=CURRENT_TIMESTAMP WHERE user_id=? AND location_id=?").run(target,uid,id)}else if(count)db.prepare("UPDATE vehicles SET location_id=NULL,updated_at=CURRENT_TIMESTAMP WHERE user_id=? AND location_id=?").run(uid,id);db.prepare("DELETE FROM vehicle_locations WHERE id=? AND user_id=?").run(id,uid);return json(res,200,{ok:true,affectedVehicles:count})}}
    if(url.pathname==="/api/private/vehicles/dashboard"&&req.method==="GET")return json(res,200,dashboardResult(uid,user))
    if(url.pathname==="/api/private/vehicles/documents"&&req.method==="GET")return json(res,200,documentsResult(uid,url))
    if(url.pathname==="/api/private/vehicles/reminders"&&req.method==="GET")return json(res,200,remindersResult(uid,url))
    if(url.pathname==="/api/private/vehicles/incomplete"&&req.method==="GET")return json(res,200,incompleteResult(uid,url))
    if(url.pathname==="/api/private/vehicles"&&req.method==="GET")return json(res,200,listResult(uid,url))
   if(url.pathname==="/api/private/vehicles"&&req.method==="POST"){const x=input(await body(req));if(x.locationId&&!location(uid,x.locationId))return json(res,400,{error:"Invalid location"});const r=db.prepare(`INSERT INTO vehicles(user_id,vehicle_number,${mutableFields}) VALUES(${Array(2+values(x).length).fill("?").join(",")})`).run(uid,x.number,...values(x));audit(uid,"vehicle_created",Number(r.lastInsertRowid));return json(res,201,{id:Number(r.lastInsertRowid)})}
   if(url.pathname==="/api/private/vehicles/import/template.xlsx"&&req.method==="GET"){const wb=new ExcelJS.Workbook();wb.creator="Vehicle Manager";const sheet=wb.addWorksheet("Vehicle Import",{views:[{state:"frozen",ySplit:1}]});sheet.addRow(IMPORT_HEADERS);sheet.getRow(1).height=32;sheet.getRow(1).font={bold:true,color:{argb:"FFFFFFFF"}};sheet.getRow(1).fill={type:"pattern",pattern:"solid",fgColor:{argb:"FF568C6B"}};sheet.getRow(1).alignment={vertical:"middle",wrapText:true};sheet.columns=IMPORT_HEADERS.map((h,i)=>({width:i===23?36:Math.max(14,Math.min(25,h.length+3))}));for(let row=2;row<=501;row++){sheet.getCell(`D${row}`).dataValidation={type:"list",allowBlank:true,formulae:['"Car,Bike,Other"']};sheet.getCell(`E${row}`).dataValidation={type:"list",allowBlank:true,formulae:['"Diesel,Petrol"']}}for(const col of[10,16,17,20,21,23,24])sheet.getColumn(col).numFmt="yyyy-mm-dd";sheet.getColumn(10).numFmt="0";sheet.autoFilter="A1:Y1";const instructions=wb.addWorksheet("Instructions");instructions.columns=[{width:34},{width:76}];instructions.addRow(["Vehicle Import Instructions",""]);instructions.mergeCells("A1:B1");instructions.getRow(1).font={bold:true,color:{argb:"FFFFFFFF"},size:14};instructions.getRow(1).fill={type:"pattern",pattern:"solid",fgColor:{argb:"FF193040"}};instructions.addRows([["Vehicle Number","Required; this is the only mandatory field"],["Vehicle Type","Optional: Car / Bike / Other"],["Car Owner Name","Optional"],["Manufacturer / Company / Model / Variant","Optional"],["Chassis Number / Engine Number","Optional; blank cells are accepted"],["Purchase Date / Current KM / Notes","Optional"],["Insurance and PUC metadata","Optional; blank cells are accepted"],["Documents","PDF/JPG/PNG files are uploaded separately inside each vehicle; they are not embedded in Excel"],["Next step","Fill vehicle details, save the file, then upload it in Import Excel."]]);instructions.getColumn(1).font={bold:true};const out=Buffer.from(await wb.xlsx.writeBuffer());res.writeHead(200,{"Content-Type":"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","Content-Disposition":"attachment; filename=vehicle-import-template.xlsx","Cache-Control":"no-store"});return res.end(out)}
   if(url.pathname==="/api/private/vehicles/import/template.csv"&&req.method==="GET"){res.writeHead(200,{"Content-Type":"text/csv; charset=utf-8","Content-Disposition":"attachment; filename=vehicle-import-template.csv","Cache-Control":"no-store"});return res.end(`${IMPORT_HEADERS.join(",")}\r\n`)}
   if(url.pathname==="/api/private/vehicles/import/preview"&&req.method==="POST"){const fd=await form(req),file=fd.get("file"),ext=file&&typeof file!=="string"?path.extname(file.name).toLowerCase():"";if(!file||typeof file==="string"||!file.size||file.size>MAX_SHEET||![".csv",".xlsx"].includes(ext))return json(res,400,{error:"A .csv or .xlsx file up to 10 MB is required"});const rows=await sheetRows(Buffer.from(await file.arrayBuffer()),ext),valid=rows.filter(r=>r.valid),numbers=valid.map(r=>r.data.vehicle_number),existing=new Set(numbers.length?db.prepare(`SELECT vehicle_number FROM vehicles WHERE user_id=? AND vehicle_number IN (${numbers.map(()=>"?").join(",")})`).all(uid,...numbers).map(r=>r.vehicle_number.toUpperCase()):[]);for(const r of valid)if(existing.has(r.data.vehicle_number)){r.duplicate=true;r.warning="Vehicle number already exists"}return json(res,200,{rows,valid:valid.length,invalid:rows.length-valid.length,duplicates:valid.filter(r=>r.duplicate).length})}
   if(url.pathname==="/api/private/vehicles/import/commit"&&req.method==="POST"){const b=await body(req),mode=b.duplicateMode==="update"?"update":"skip",rows=Array.isArray(b.rows)?b.rows:[];let created=0,updated=0,skipped=0;db.exec("BEGIN");try{for(const raw of rows){let x;try{x=input(raw.data||raw)}catch{skipped++;continue}const old=db.prepare("SELECT id FROM vehicles WHERE user_id=? AND vehicle_number=?").get(uid,x.number);if(old){if(mode==="skip"){skipped++;continue}db.prepare(`UPDATE vehicles SET ${importFields.map(f=>`${f}=?`).join(",")},updated_at=CURRENT_TIMESTAMP WHERE id=? AND user_id=?`).run(...importValues(x),old.id,uid);updated++}else{db.prepare(`INSERT INTO vehicles(user_id,vehicle_number,${importFields.join(",")}) VALUES(${Array(2+importValues(x).length).fill("?").join(",")})`).run(uid,x.number,...importValues(x));created++}}db.exec("COMMIT")}catch(e){db.exec("ROLLBACK");throw e}audit(uid,"vehicles_imported");return json(res,200,{created,updated,skipped})}
   if(url.pathname==="/api/private/vehicles/export"&&req.method==="GET"){const rows=db.prepare("SELECT v.vehicle_number 'Vehicle Number',v.vehicle_name 'Car Owner Name',v.type 'Vehicle Type',v.fuel_type 'Fuel Type',v.manufacturer Manufacturer,v.brand 'Company/Brand',v.model Model,v.variant Variant,v.purchase_date 'Purchase Date',v.current_km 'Current KM',v.chassis_number 'Chassis Number',v.engine_number 'Engine Number',v.first_party_insurer 'First Party Insurance Company',v.first_party_policy_number 'First Party Policy No.',v.first_party_start_date 'First Party Start Date',v.first_party_expiry_date 'First Party Expiry Date',v.third_party_insurer 'Third Party Insurance Company',v.third_party_policy_number 'Third Party Policy No.',v.third_party_start_date 'Third Party Start Date',v.third_party_expiry_date 'Third Party Expiry Date',v.puc_number 'PUC Number',v.puc_issue_date 'PUC Issue Date',v.puc_expiry_date 'PUC Expiry Date',v.notes Notes,COUNT(d.id) 'Document Count' FROM vehicles v LEFT JOIN vehicle_documents d ON d.vehicle_id=v.id AND d.user_id=v.user_id AND d.deleted_at IS NULL WHERE v.user_id=? GROUP BY v.id ORDER BY v.vehicle_number").all(uid);if(url.searchParams.get("format")==="xlsx"){const wb=new ExcelJS.Workbook(),ws=wb.addWorksheet("Vehicles"),headers=Object.keys(rows[0]||Object.fromEntries(IMPORT_HEADERS.slice(1).map(h=>[h,""])));ws.addRow(headers);for(const row of rows)ws.addRow(headers.map(h=>row[h]));ws.getRow(1).font={bold:true};ws.columns.forEach(c=>c.width=20);const out=Buffer.from(await wb.xlsx.writeBuffer());res.writeHead(200,{"Content-Type":"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","Content-Disposition":"attachment; filename=my-vehicles.xlsx","Cache-Control":"no-store"});return res.end(out)}const headers=Object.keys(rows[0]||Object.fromEntries(IMPORT_HEADERS.slice(1).map(h=>[h,""]))),out=[headers.map(csv).join(","),...rows.map(r=>headers.map(h=>csv(r[h])).join(","))].join("\r\n");res.writeHead(200,{"Content-Type":"text/csv; charset=utf-8","Content-Disposition":"attachment; filename=my-vehicles.csv","Cache-Control":"no-store"});return res.end(`\ufeff${out}`)}
   const vm=url.pathname.match(/^\/api\/private\/vehicles\/(\d+)$/);if(vm){const id=Number(vm[1]);if(req.method==="GET"){const v=vehicle(uid,id);if(!v)return json(res,404,{error:"Vehicle not found"});const documents=db.prepare("SELECT d.*,x.original_name,x.file_size,x.mime_type,x.id version_id FROM vehicle_documents d LEFT JOIN document_versions x ON x.document_id=d.id AND x.is_active=1 AND x.deleted_at IS NULL WHERE d.vehicle_id=? AND d.user_id=? AND d.deleted_at IS NULL ORDER BY d.created_at DESC").all(id,v.user_id);return json(res,200,{vehicle:v,documents})}if(req.method==="PUT"){const permitted=vehicle(uid,id);if(!permitted)return json(res,404,{error:"Vehicle not found"});if(!canEdit(uid,id))return json(res,403,{error:"Editor permission required"});const x=input(await body(req));if(x.locationId&&!location(permitted.user_id,x.locationId))return json(res,400,{error:"Invalid location"});db.prepare(`UPDATE vehicles SET vehicle_number=?,${mutableFields.split(",").map(f=>`${f}=?`).join(",")},updated_at=CURRENT_TIMESTAMP WHERE id=? AND user_id=?`).run(x.number,...values(x),id,permitted.user_id);audit(permitted.user_id,"vehicle_updated",id);return json(res,200,{ok:true})}if(req.method==="DELETE"){if(!isOwner(uid,id))return json(res,403,{error:"Only the vehicle owner can delete it"});const r=db.prepare("DELETE FROM vehicles WHERE id=? AND user_id=?").run(id,uid);if(!r.changes)return json(res,404,{error:"Vehicle not found"});audit(uid,"vehicle_deleted",id);return json(res,200,{ok:true})}}
   const docs=url.pathname.match(/^\/api\/private\/vehicles\/(\d+)\/documents$/);if(docs&&req.method==="POST"){const vid=Number(docs[1]);if(!vehicle(uid,vid))return json(res,404,{error:"Vehicle not found"});if(!canEdit(uid,vid))return json(res,403,{error:"Editor permission required"});const ownerId=vehicle(uid,vid).user_id,fd=await form(req),f=await checkedFile(fd.get("file")),name=clean(fd.get("name"),120)||clean(fd.get("category"),80);if(!name)throw new Error("Document name is required");await writeFile(path.join(store,f.stored),f.bytes,{flag:"wx"});let did;try{db.exec("BEGIN");const d=db.prepare("INSERT INTO vehicle_documents(user_id,vehicle_id,name,category,document_number,issue_date,expiry_date,notes) VALUES(?,?,?,?,?,?,?,?)").run(ownerId,vid,name,clean(fd.get("category"),80)||"Other",clean(fd.get("document_number"),100),clean(fd.get("issue_date"),10),clean(fd.get("expiry_date"),10)||null,clean(fd.get("notes")));did=Number(d.lastInsertRowid);db.prepare("INSERT INTO document_versions(document_id,stored_name,original_name,mime_type,file_size) VALUES(?,?,?,?,?)").run(did,f.stored,f.original,f.mime,f.size);db.exec("COMMIT")}catch(e){db.exec("ROLLBACK");await unlink(path.join(store,f.stored)).catch(()=>{});throw e}audit(ownerId,"document_uploaded",vid,did);return json(res,201,{id:did})}
   const rep=url.pathname.match(/^\/api\/private\/vehicles\/(\d+)\/documents\/(\d+)\/replace$/);if(rep&&req.method==="POST"){const vid=Number(rep[1]),did=Number(rep[2]);if(!document(uid,vid,did))return json(res,404,{error:"Document not found"});if(!canEdit(uid,vid))return json(res,403,{error:"Editor permission required"});const ownerId=vehicle(uid,vid).user_id,fd=await form(req),f=await checkedFile(fd.get("file"));await writeFile(path.join(store,f.stored),f.bytes,{flag:"wx"});try{db.exec("BEGIN");db.prepare("UPDATE document_versions SET is_active=0 WHERE document_id=? AND is_active=1").run(did);db.prepare("INSERT INTO document_versions(document_id,stored_name,original_name,mime_type,file_size) VALUES(?,?,?,?,?)").run(did,f.stored,f.original,f.mime,f.size);db.exec("COMMIT")}catch(e){db.exec("ROLLBACK");await unlink(path.join(store,f.stored)).catch(()=>{});throw e}audit(ownerId,"document_replaced",vid,did);return json(res,200,{ok:true})}
   const hist=url.pathname.match(/^\/api\/private\/vehicles\/(\d+)\/documents\/(\d+)\/versions$/);if(hist&&req.method==="GET"){const vid=Number(hist[1]),did=Number(hist[2]);if(!document(uid,vid,did))return json(res,404,{error:"Document not found"});return json(res,200,{versions:db.prepare("SELECT id,original_name,mime_type,file_size,is_active,created_at FROM document_versions WHERE document_id=? AND deleted_at IS NULL ORDER BY created_at DESC,id DESC").all(did)})}
   const oldFile=url.pathname.match(/^\/api\/private\/vehicles\/(\d+)\/documents\/(\d+)\/versions\/(\d+)\/(view|download)$/);if(oldFile&&["GET","HEAD"].includes(req.method)){const vid=Number(oldFile[1]),did=Number(oldFile[2]),versionId=Number(oldFile[3]),mode=oldFile[4];if(!document(uid,vid,did))return json(res,404,{error:"Document not found"});const v=db.prepare("SELECT * FROM document_versions WHERE id=? AND document_id=? AND deleted_at IS NULL").get(versionId,did),p=v&&path.join(store,path.basename(v.stored_name));if(!v||!existsSync(p))return json(res,404,{error:"File not found"});audit(uid,mode==="view"?"document_version_viewed":"document_version_downloaded",vid,did);res.writeHead(200,{"Content-Type":v.mime_type,"Content-Length":(await stat(p)).size,"Content-Disposition":`${mode==="view"?"inline":"attachment"}; filename*=UTF-8''${encodeURIComponent(v.original_name)}`,"Cache-Control":"no-store","X-Content-Type-Options":"nosniff"});if(req.method==="HEAD")return res.end();return createReadStream(p).pipe(res)}
   const file=url.pathname.match(/^\/api\/private\/vehicles\/(\d+)\/documents\/(\d+)\/(view|download)$/);if(file&&["GET","HEAD"].includes(req.method)){const vid=Number(file[1]),did=Number(file[2]);if(!document(uid,vid,did))return json(res,404,{error:"Document not found"});const v=db.prepare("SELECT * FROM document_versions WHERE document_id=? AND is_active=1 AND deleted_at IS NULL").get(did),p=v&&path.join(store,path.basename(v.stored_name));if(!v||!existsSync(p))return json(res,404,{error:"File not found"});audit(uid,file[3]==="view"?"document_viewed":"document_downloaded",vid,did);res.writeHead(200,{"Content-Type":v.mime_type,"Content-Length":(await stat(p)).size,"Content-Disposition":`${file[3]==="view"?"inline":"attachment"}; filename*=UTF-8''${encodeURIComponent(v.original_name)}`,"Cache-Control":"no-store","X-Content-Type-Options":"nosniff"});if(req.method==="HEAD")return res.end();return createReadStream(p).pipe(res)}
   const del=url.pathname.match(/^\/api\/private\/vehicles\/(\d+)\/documents\/(\d+)$/);if(del&&req.method==="DELETE"){const vid=Number(del[1]),did=Number(del[2]);if(!document(uid,vid,did))return json(res,404,{error:"Document not found"});if(!isOwner(uid,vid))return json(res,403,{error:"Only the vehicle owner can delete documents"});db.prepare("UPDATE vehicle_documents SET deleted_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=? AND user_id=?").run(did,uid);db.prepare("UPDATE document_versions SET is_active=0,deleted_at=CURRENT_TIMESTAMP WHERE document_id=?").run(did);audit(uid,"document_deleted",vid,did);return json(res,200,{ok:true})}
   return json(res,404,{error:"Private vehicle endpoint not found"});
  }catch(e){const conflict=String(e.message).includes("UNIQUE constraint failed");return json(res,conflict?409:400,{error:conflict?"Vehicle number already exists in your account":e.message})}
 }
}
