import {useEffect,useState} from "react";
import {ArrowLeft,Car,Download,ExternalLink,FileText,HardDrive,Search,ShieldCheck,Users} from "lucide-react";

type ApiError=Error&{status?:number};
async function api(url:string,options?:RequestInit){const response=await fetch(url,options),data=await response.json().catch(()=>({}));if(!response.ok){const error=new Error(data.error||"Request failed") as ApiError;error.status=response.status;throw error}return data}
const bytes=(value:number)=>{if(!value)return"0 B";const units=["B","KB","MB","GB","TB"],index=Math.min(Math.floor(Math.log(value)/Math.log(1024)),units.length-1);return`${(value/1024**index).toFixed(index?2:0)} ${units[index]}`};
const date=(value?:string)=>value?new Date(value.includes("T")?value:`${value.replace(" ","T")}Z`).toLocaleDateString("en-IN",{day:"2-digit",month:"short",year:"numeric"}):"—";
const Badge=({children}:{children:React.ReactNode})=><span className={`avp-badge avp-${String(children).toLowerCase().replaceAll(" ","-")}`}>{children}</span>;

function Pager({page,totalPages,onChange}:{page:number;totalPages:number;onChange:(page:number)=>void}){if(totalPages<=1)return null;return <div className="avp-pager"><button disabled={page<=1} onClick={()=>onChange(page-1)}>Previous</button><span>Page {page} of {totalPages}</span><button disabled={page>=totalPages} onClick={()=>onChange(page+1)}>Next</button></div>}

function PortalOverview(){
 const[data,setData]=useState<any>(),[error,setError]=useState(""),[q,setQ]=useState(""),[status,setStatus]=useState(""),[billingStatus,setBillingStatus]=useState(""),[page,setPage]=useState(1);
 useEffect(()=>{const timer=setTimeout(()=>{const params=new URLSearchParams({page:String(page),pageSize:"20"});if(q)params.set("q",q);if(status)params.set("status",status);if(billingStatus)params.set("billingStatus",billingStatus);setError("");api(`/api/admin/vehicle-portal?${params}`).then(setData).catch(error=>setError(error.message))},250);return()=>clearTimeout(timer)},[q,status,billingStatus,page]);
 if(error)return <div className="avp-error">{error}</div>;if(!data)return <div className="avp-loading">Loading Vehicle Portal…</div>;
 const cards=[["Total Organizations",data.summary.totalOrganizations,Users],["Active Organizations",data.summary.activeOrganizations,ShieldCheck],["Disabled Organizations",data.summary.disabledOrganizations,Users],["Total Vehicles",data.summary.totalVehicles,Car],["Total Documents",data.summary.totalDocuments,FileText],["Total Storage",bytes(data.summary.totalStorageBytes),HardDrive],["Users / Drivers",data.summary.totalOrganizationUsers,Users]];
 return <section className="avp">
  <div className="avp-hero"><div><small>ADMIN MODULE</small><h2>Vehicle Portal</h2><p>Customer accounts, vehicles, documents, usage and billing information.</p></div></div>
  <div className="avp-stats">{cards.map(([label,value,Icon]:any)=><article key={label}><Icon/><span>{label}</span><strong>{value}</strong></article>)}</div>
  <section className="avp-panel"><div className="avp-panel-head"><div><h3>Customers</h3><p>{data.total} matching Vehicle Portal users</p></div></div>
   <div className="avp-filters"><label><Search/><input value={q} onChange={event=>{setQ(event.target.value);setPage(1)}} placeholder="Search name, email or vehicle number"/></label><select value={status} onChange={event=>{setStatus(event.target.value);setPage(1)}}><option value="">All statuses</option><option value="active">Active</option><option value="disabled">Disabled</option></select><select value={billingStatus} onChange={event=>{setBillingStatus(event.target.value);setPage(1)}}><option value="">All billing statuses</option>{["Not Set","Active","Pending","Paid","Due","Overdue","Suspended"].map(value=><option key={value}>{value}</option>)}</select></div>
   <div className="avp-table-wrap"><table><thead><tr><th>S.No.</th><th>Organization</th><th>Primary Admin</th><th>Email</th><th>Status</th><th>Vehicles</th><th>Cars</th><th>Bikes</th><th>Other</th><th>Documents</th><th>Storage Used</th><th>Users</th><th>Joined</th><th>Last Login</th><th>Plan</th><th>Billing</th><th>Action</th></tr></thead><tbody>{data.items.map((user:any,index:number)=><tr key={user.id}><td>{(data.page-1)*data.pageSize+index+1}</td><td><strong>{user.organization_name||user.name}</strong></td><td>{user.name}</td><td>{user.email}</td><td><Badge>{user.active?"Active":"Disabled"}</Badge></td><td>{user.total_vehicles}</td><td>{user.cars}</td><td>{user.bikes}</td><td>{user.other}</td><td>{user.documents}</td><td>{bytes(user.storage_bytes)}</td><td>{user.organization_users}</td><td>{date(user.created_at)}</td><td>{date(user.last_login_at)}</td><td>{user.plan||"Not Set"}</td><td><Badge>{user.billing_status}</Badge></td><td><a className="avp-action" href={`/admin/vehicle-portal/users/${user.id}`}>View organization</a></td></tr>)}</tbody></table>{!data.items.length&&<div className="avp-empty">No organizations match these filters.</div>}</div>
   <Pager page={data.page} totalPages={data.totalPages} onChange={setPage}/>
  </section>
 </section>
}

function VehicleProfile({userId,vehicleId}:{userId:number;vehicleId:number}){
 const[data,setData]=useState<any>(),[error,setError]=useState("");useEffect(()=>{api(`/api/admin/vehicle-portal/users/${userId}/vehicles/${vehicleId}`).then(setData).catch(error=>setError(error.message))},[userId,vehicleId]);
 if(error)return <div className="avp-error">{error}</div>;if(!data)return <div className="avp-loading">Loading vehicle profile…</div>;const vehicle=data.vehicle;
 const fields=[["Car Owner Name",vehicle.vehicle_name],["Type",vehicle.type],["Registration",vehicle.registration_status],["Manufacturer",vehicle.manufacturer],["Company / Brand",vehicle.brand||vehicle.make],["Model",vehicle.model],["Variant",vehicle.variant],["Current KM",vehicle.current_km],["Chassis Number",vehicle.chassis_number],["Engine Number",vehicle.engine_number],["Purchase Date",vehicle.purchase_date],["Location",vehicle.location_name||"Unassigned"],["First Party Company",vehicle.first_party_insurer],["First Party Policy",vehicle.first_party_policy_number],["First Party Expiry",vehicle.first_party_expiry_date],["Third Party Company",vehicle.third_party_insurer],["Third Party Policy",vehicle.third_party_policy_number],["Third Party Expiry",vehicle.third_party_expiry_date],["PUC Number",vehicle.puc_number],["PUC Expiry",vehicle.puc_expiry_date]];
 return <section className="avp avp-detail"><a className="avp-back" href={`/admin/vehicle-portal/users/${userId}`}><ArrowLeft/> Back to customer</a><div className="avp-hero"><div><small>AUTHORIZED ADMIN VIEW</small><h2>{vehicle.vehicle_number}</h2><p>{[vehicle.vehicle_name,vehicle.brand||vehicle.make,vehicle.model,vehicle.type].filter(Boolean).join(" · ")||"Vehicle profile"}</p></div></div><section className="avp-panel"><h3>Vehicle Information</h3><dl className="avp-details">{fields.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value||"—"}</dd></div>)}</dl></section><section className="avp-panel"><div className="avp-panel-head"><div><h3>Documents & Version History</h3><p>Files remain private and are served only through authorized admin endpoints.</p></div></div>{data.documents.length?<div className="avp-doc-cards">{data.documents.map((document:any)=><article key={document.id}><div><strong>{document.name}</strong><span>{document.category} · {document.original_name||"No active file"}</span></div>{document.original_name&&<div className="avp-actions"><a href={`/api/admin/vehicle-portal/users/${userId}/documents/${document.id}/view`} target="_blank" rel="noreferrer"><ExternalLink/> View</a><a href={`/api/admin/vehicle-portal/users/${userId}/documents/${document.id}/download`}><Download/> Download</a></div>}<ul>{document.versions.map((version:any)=><li key={version.id}><span>{version.original_name}</span><span>{version.is_active&&!version.deleted_at?"Current":"Archived"} · {bytes(version.file_size)} · {date(version.created_at)}</span></li>)}</ul></article>)}</div>:<div className="avp-empty">No documents uploaded.</div>}</section></section>
}

function CustomerDetail({userId}:{userId:number}){
 const[data,setData]=useState<any>(),[error,setError]=useState(""),[message,setMessage]=useState(""),[vehiclePage,setVehiclePage]=useState(1),[documentPage,setDocumentPage]=useState(1),[billing,setBilling]=useState<any>({});
 const vehicleId=Number(new URLSearchParams(location.search).get("vehicleId"));
 const load=()=>{const params=new URLSearchParams({vehiclePage:String(vehiclePage),documentPage:String(documentPage),pageSize:"20"});setError("");api(`/api/admin/vehicle-portal/users/${userId}?${params}`).then(result=>{setData(result);setBilling({plan:result.user.plan||"",billingCycle:result.user.billing_cycle||"",amount:result.user.amount||0,billingStatus:result.user.billing_status||"Not Set",nextBillingDate:result.user.next_billing_date||"",dueDate:result.user.due_date||"",notes:result.user.billing_notes||""})}).catch(error=>setError(error.message))};
 useEffect(load,[userId,vehiclePage,documentPage]);if(vehicleId)return <VehicleProfile userId={userId} vehicleId={vehicleId}/>;if(error)return <div className="avp-error">{error}</div>;if(!data)return <div className="avp-loading">Loading customer…</div>;
 const save=async(event:React.FormEvent)=>{event.preventDefault();setMessage("Saving…");try{await api(`/api/admin/vehicle-portal/users/${userId}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({billing})});setMessage("Billing information saved.");load()}catch(error:any){setMessage(error.message)}};
 const toggle=async()=>{if(!confirm(`${data.user.active?"Disable":"Enable"} this customer account?`))return;await api(`/api/admin/vehicle-portal/users/${userId}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({active:!data.user.active})});load()};
 return <section className="avp avp-detail"><a className="avp-back" href="/admin/vehicle-portal"><ArrowLeft/> Back to organizations</a><div className="avp-hero avp-customer-head"><div><small>ORGANIZATION</small><h2>{data.user.organization_name||data.user.name}</h2><p>Organization Admin: {data.user.name} · {data.user.email}</p></div><button className={data.user.active?"avp-danger":"avp-primary"} onClick={toggle}>{data.user.active?"Disable organization":"Enable organization"}</button></div>
  <div className="avp-summary-grid"><section className="avp-panel"><h3>Organization</h3><dl className="avp-details"><div><dt>Organization Name</dt><dd>{data.user.organization_name||data.user.name}</dd></div><div><dt>Admin Name</dt><dd>{data.user.name}</dd></div><div><dt>Email</dt><dd>{data.user.email}</dd></div><div><dt>Mobile</dt><dd>{data.user.mobile||"—"}</dd></div><div><dt>Status</dt><dd><Badge>{data.user.active?"Active":"Disabled"}</Badge></dd></div><div><dt>Created Date</dt><dd>{date(data.user.created_at)}</dd></div><div><dt>Last Login</dt><dd>{date(data.user.last_login_at)}</dd></div></dl></section>
   <section className="avp-panel"><h3>Vehicle Summary</h3><div className="avp-mini-stats">{[["Total",data.vehicleSummary.totalVehicles],["Cars",data.vehicleSummary.cars],["Bikes",data.vehicleSummary.bikes],["Other",data.vehicleSummary.other]].map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div></section>
   <section className="avp-panel"><h3>Documents & Storage</h3><dl className="avp-details"><div><dt>Total Documents</dt><dd>{data.storage.totalDocuments}</dd></div><div><dt>Active Documents</dt><dd>{data.storage.activeDocuments}</dd></div><div><dt>Archived / Old Versions</dt><dd>{data.storage.archivedVersions}</dd></div><div><dt>Active Storage</dt><dd>{bytes(data.storage.activeStorageBytes)}</dd></div><div><dt>Archived Storage</dt><dd>{bytes(data.storage.archivedStorageBytes)}</dd></div><div><dt>Total Storage</dt><dd>{bytes(data.storage.totalStorageBytes)}</dd></div></dl></section>
  </div>
  <div className="avp-summary-grid"><section className="avp-panel"><h3>Organization Users</h3><div className="avp-mini-stats">{[["Organization Admin",data.userSummary.organizationAdmins],["Drivers / Employees",data.userSummary.driversEmployees],["Viewers",data.userSummary.viewers],["Editors",data.userSummary.editors]].map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>{data.organizationUsers.length?<ul className="avp-clean-list">{data.organizationUsers.map((member:any)=><li key={member.id}><span><b>{member.name}</b><small>{member.email}</small></span><strong>{member.organization_role.replace("ORGANIZATION_","")}</strong></li>)}</ul>:<div className="avp-empty">No drivers or employees created.</div>}</section><section className="avp-panel"><h3>Locations ({data.locations.length})</h3>{data.locations.length?<ul className="avp-clean-list">{data.locations.map((item:any)=><li key={item.id}><span>{item.name}</span><strong>{item.vehicle_count} vehicles</strong></li>)}</ul>:<div className="avp-empty">No locations created.</div>}</section><section className="avp-panel"><h3>Sharing</h3>{data.sharing.length?<ul className="avp-clean-list">{data.sharing.map((item:any)=><li key={item.id}><span><b>{item.grantee_name}</b><small>{item.grantee_email} · {item.location_name}</small></span><strong>{item.permission} · {item.vehicle_count}</strong></li>)}</ul>:<div className="avp-empty">No sharing access configured.</div>}</section></div>
  <section className="avp-panel"><div className="avp-panel-head"><div><h3>Vehicles</h3><p>{data.vehicles.total} vehicles owned by this customer</p></div></div><div className="avp-table-wrap"><table><thead><tr><th>Vehicle Number</th><th>Car Owner Name</th><th>Type</th><th>Manufacturer</th><th>Company</th><th>Model</th><th>Location</th><th>Documents</th><th>Expiry Status</th></tr></thead><tbody>{data.vehicles.items.map((vehicle:any)=><tr key={vehicle.id}><td><a className="avp-vehicle-link" href={`/admin/vehicle-portal/users/${userId}?vehicleId=${vehicle.id}`}>{vehicle.vehicle_number}</a></td><td>{vehicle.vehicle_name||"—"}</td><td>{vehicle.type||"—"}</td><td>{vehicle.manufacturer||"—"}</td><td>{vehicle.brand||vehicle.make||"—"}</td><td>{vehicle.model||"—"}</td><td>{vehicle.location_name||"Unassigned"}</td><td>{vehicle.document_count}</td><td><Badge>{vehicle.expiry_status}</Badge></td></tr>)}</tbody></table>{!data.vehicles.items.length&&<div className="avp-empty">No vehicles added.</div>}</div><Pager page={data.vehicles.page} totalPages={data.vehicles.totalPages} onChange={setVehiclePage}/></section>
  <section className="avp-panel"><div className="avp-panel-head"><div><h3>Documents</h3><p>Current documents available through protected admin access.</p></div></div><div className="avp-table-wrap"><table><thead><tr><th>Vehicle Number</th><th>Document Type</th><th>File Name</th><th>File Size</th><th>Upload Date</th><th>Status</th><th>Actions</th></tr></thead><tbody>{data.documents.items.map((document:any)=><tr key={document.id}><td>{document.vehicle_number}</td><td>{document.category}</td><td>{document.original_name||"—"}</td><td>{bytes(document.file_size)}</td><td>{date(document.created_at)}</td><td><Badge>{document.status}</Badge></td><td>{document.original_name?<div className="avp-actions"><a href={`/api/admin/vehicle-portal/users/${userId}/documents/${document.id}/view`} target="_blank" rel="noreferrer"><ExternalLink/> View</a><a href={`/api/admin/vehicle-portal/users/${userId}/documents/${document.id}/download`}><Download/> Download</a></div>:"—"}</td></tr>)}</tbody></table>{!data.documents.items.length&&<div className="avp-empty">No documents uploaded.</div>}</div><Pager page={data.documents.page} totalPages={data.documents.totalPages} onChange={setDocumentPage}/></section>
  <form className="avp-panel avp-billing" onSubmit={save}><div className="avp-panel-head"><div><h3>Billing</h3><p>Billing-ready records only. No payment gateway or checkout is enabled.</p></div><span>{message}</span></div><div className="avp-form-grid"><label>Plan<input value={billing.plan} onChange={event=>setBilling({...billing,plan:event.target.value})}/></label><label>Billing Cycle<input value={billing.billingCycle} onChange={event=>setBilling({...billing,billingCycle:event.target.value})} placeholder="Monthly / Annual"/></label><label>Vehicle Count<input value={data.vehicleSummary.totalVehicles} readOnly/></label><label>Storage Used<input value={bytes(data.storage.totalStorageBytes)} readOnly/></label><label>User Count<input value={data.userSummary.driversEmployees+data.userSummary.organizationAdmins} readOnly/></label><label>Amount<input type="number" min="0" step="0.01" value={billing.amount} onChange={event=>setBilling({...billing,amount:event.target.value})}/></label><label>Billing Status<select value={billing.billingStatus} onChange={event=>setBilling({...billing,billingStatus:event.target.value})}>{["Not Set","Active","Pending","Paid","Due","Overdue","Suspended"].map(value=><option key={value}>{value}</option>)}</select></label><label>Next Billing Date<input type="date" value={billing.nextBillingDate} onChange={event=>setBilling({...billing,nextBillingDate:event.target.value})}/></label><label>Due Date<input type="date" value={billing.dueDate} onChange={event=>setBilling({...billing,dueDate:event.target.value})}/></label><label className="wide">Notes<textarea rows={4} value={billing.notes} onChange={event=>setBilling({...billing,notes:event.target.value})}/></label></div><button className="avp-primary">Save billing information</button></form>
 </section>
}

export function AdminVehiclePortal(){const match=location.pathname.match(/^\/admin\/vehicle-portal\/users\/(\d+)$/);return match?<CustomerDetail userId={Number(match[1])}/>:<PortalOverview/>}
