import {useEffect,useMemo,useState} from "react";
import {ArrowLeft,KeyRound,Mail,MapPin,Pencil,Plus,Power,RotateCcw,Share2,Trash2,UserPlus} from "lucide-react";

async function api(url:string,options?:RequestInit){const response=await fetch(url,options),data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||"Request failed");return data}
const emptyShare={id:0,locationId:"",granteeUserId:"",permission:"view",scope:"location",vehicleIds:[] as number[]};
const emptyUser={name:"",email:"",mobile:"",password:"",permission:"view",scope:"location",locationId:"",vehicleIds:[] as number[]};
const emptyProfile={name:"",email:"",mobile:"",date_of_birth:"",organization_name:"",designation:"",address:"",city:"",state:"",postal_code:""};
const accountView=()=>location.hash==="#sharing"?"sharing":location.hash==="#locations"?"locations":"settings";

export function VehicleAccount(){
 const[message,setMessage]=useState(""),[me,setMe]=useState<any>({}),[profile,setProfile]=useState<any>(emptyProfile),[view,setView]=useState(accountView),[data,setData]=useState<any>({locations:[],unassigned:0}),[sharing,setSharing]=useState<any>({locations:[],vehicles:[],users:[],shares:[],received:[],managedUsers:[]}),[name,setName]=useState(""),[share,setShare]=useState(emptyShare),[newUser,setNewUser]=useState(emptyUser),[saving,setSaving]=useState(false),[savingProfile,setSavingProfile]=useState(false);
 const managed=me.account_kind==="managed";
 const load=async()=>{try{const[account,locations,access]=await Promise.all([api("/api/auth/me"),api("/api/private/vehicles/locations"),api("/api/private/vehicles/sharing")]);setMe(account.user);setProfile(Object.fromEntries(Object.keys(emptyProfile).map(key=>[key,account.user?.[key]??""])));setData(locations);setSharing(access)}catch(error:any){setMessage(error.message)}};
 useEffect(()=>{load();const sync=()=>setView(accountView());window.addEventListener("hashchange",sync);return()=>window.removeEventListener("hashchange",sync)},[]);
 const availableVehicles=useMemo(()=>sharing.vehicles.filter((vehicle:any)=>String(vehicle.location_id)===String(share.locationId)||share.vehicleIds.includes(vehicle.id)),[sharing.vehicles,share.locationId,share.vehicleIds]);
 const newUserVehicles=useMemo(()=>sharing.vehicles.filter((vehicle:any)=>String(vehicle.location_id)===String(newUser.locationId)),[sharing.vehicles,newUser.locationId]);
 const remove=async(item:any)=>{let action:any={};if(item.vehicle_count){const choice=prompt(`This location is assigned to ${item.vehicle_count} vehicles. Type UNASSIGN, or enter another location name.`);if(!choice)return;if(choice.trim().toUpperCase()==="UNASSIGN")action={action:"unassign"};else{const target=data.locations.find((location:any)=>location.id!==item.id&&location.name.toLowerCase()===choice.trim().toLowerCase());if(!target){setMessage("Destination location not found.");return}action={action:"move",moveToLocationId:target.id}}}try{await api(`/api/private/vehicles/locations/${item.id}`,{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify(action)});await load()}catch(error:any){setMessage(error.message)}};
 const saveShare=async(event:React.FormEvent)=>{event.preventDefault();setSaving(true);setMessage("");try{await api(share.id?`/api/private/vehicles/sharing/${share.id}`:"/api/private/vehicles/sharing",{method:share.id?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(share)});setShare(emptyShare);setMessage("Sharing access saved.");await load()}catch(error:any){setMessage(error.message)}finally{setSaving(false)}};
 const editShare=(item:any)=>setShare({id:item.id,locationId:String(item.location_id),granteeUserId:String(item.grantee_user_id),permission:item.permission,scope:item.scope,vehicleIds:item.vehicleIds.map(Number)});
 const revoke=async(id:number)=>{if(!confirm("Revoke this user's GaadiFile access?"))return;try{await api(`/api/private/vehicles/sharing/${id}`,{method:"DELETE"});if(share.id===id)setShare(emptyShare);setMessage("GaadiFile access revoked.");await load()}catch(error:any){setMessage(error.message)}};
 const userAction=async(userId:number,action:string,active?:boolean)=>{try{const result=await api(`/api/private/vehicles/sharing/users/${userId}${action?`/${action}`:""}`,active===undefined?{method:"POST"}:{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({active})});setMessage(result.message||"User updated successfully.");await load()}catch(error:any){setMessage(error.message)}};
 const createUser=async(event:React.FormEvent)=>{event.preventDefault();setSaving(true);setMessage("");try{const result=await api("/api/private/vehicles/sharing/users",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(newUser)});setNewUser(emptyUser);setMessage(result.message);await load()}catch(error:any){setMessage(error.message)}finally{setSaving(false)}};
 const saveProfile=async(event:React.FormEvent)=>{event.preventDefault();setSavingProfile(true);setMessage("");try{const result=await api("/api/auth/profile",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(profile)});setMe(result.user);setProfile(Object.fromEntries(Object.keys(emptyProfile).map(key=>[key,result.user?.[key]??""])));setMessage("Profile updated successfully.")}catch(error:any){setMessage(error.message)}finally{setSavingProfile(false)}};
 return <main className="vm vm-settings"><header><div><img className="vm-header-brand-logo" src="/pwa/icon-192.png" alt="" aria-hidden="true"/><span><b>{view==="sharing"?"Sharing & Users":view==="locations"?"Locations":"GaadiFile Settings"}</b><small>GaadiFile · {managed?"My assigned access":view==="sharing"?"Create users and manage vehicle access":view==="locations"?"Manage your private garage locations":"Profile and account security"}</small></span></div><a href="/vehicles"><ArrowLeft/> My vehicles</a></header><section className="vm-wrap vm-settings-grid">
  {view==="settings"&&<article className="vm-settings-card vm-profile-settings"><KeyRound/><h2>User Profile</h2><p>Manage your personal and company information.</p><form className="vm-profile-form" onSubmit={saveProfile}><label>Full Name *<input required value={profile.name} onChange={event=>setProfile({...profile,name:event.target.value})}/></label><label>Email Address *<input type="email" required value={profile.email} onChange={event=>setProfile({...profile,email:event.target.value})}/></label><label>Phone Number<input type="tel" value={profile.mobile} onChange={event=>setProfile({...profile,mobile:event.target.value})}/></label><label>Date of Birth<input type="date" value={profile.date_of_birth} onChange={event=>setProfile({...profile,date_of_birth:event.target.value})}/></label><label>Company Name<input value={profile.organization_name} onChange={event=>setProfile({...profile,organization_name:event.target.value})}/></label><label>Designation<input value={profile.designation} onChange={event=>setProfile({...profile,designation:event.target.value})}/></label><label className="wide">Address<textarea rows={3} value={profile.address} onChange={event=>setProfile({...profile,address:event.target.value})}/></label><label>City<input value={profile.city} onChange={event=>setProfile({...profile,city:event.target.value})}/></label><label>State<input value={profile.state} onChange={event=>setProfile({...profile,state:event.target.value})}/></label><label>PIN / Postal Code<input value={profile.postal_code} onChange={event=>setProfile({...profile,postal_code:event.target.value})}/></label><label>Account Type<input readOnly value={managed?"Assigned User":me.role==="admin"?"Administrator":"Customer"}/></label><button className="wide" disabled={savingProfile}>{savingProfile?"Saving…":"Save Profile"}</button></form><h3>Change Password</h3><form className="vm-password-form" onSubmit={async event=>{event.preventDefault();const values=Object.fromEntries(new FormData(event.currentTarget));if(values.newPassword!==values.confirmPassword){setMessage("New passwords do not match");return}try{await api("/api/auth/change-password",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(values)});setMessage("Password updated successfully.");event.currentTarget.reset()}catch(error:any){setMessage(error.message)}}}><input name="currentPassword" type="password" placeholder="Current password" required/><input name="newPassword" type="password" minLength={12} placeholder="New password (12+ characters)" required/><input name="confirmPassword" type="password" minLength={12} placeholder="Confirm new password" required/><button>Change password</button></form></article>}
  {managed?<article className="vm-settings-card vm-sharing-list"><Share2/><h2>My Assigned Access</h2>{sharing.received.map((item:any)=><div key={item.id}><span><b>{item.location_name}</b><small>{item.permission==="editor"?"Editor":"View Only"} · {item.scope==="selected"?"Selected Vehicles":"Entire Location"} · {item.vehicle_count} vehicles</small><small>{item.vehicleNumbers?.length?item.vehicleNumbers.join(", "):"No assigned vehicles"}</small></span></div>)}{!sharing.received.length&&<p>No vehicle access is currently assigned.</p>}<a className="vm-button primary" href="/api/logout">Logout</a></article>:<>
  {view==="locations"&&<article className="vm-settings-card vm-locations-page" id="locations"><MapPin/><h2>Locations</h2><p>Manage private garage locations. Unassigned vehicles: {data.unassigned}.</p><form className="vm-location-add" onSubmit={async event=>{event.preventDefault();try{await api("/api/private/vehicles/locations",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name})});setName("");await load()}catch(error:any){setMessage(error.message)}}}><input placeholder="e.g. Punjab" value={name} onChange={event=>setName(event.target.value)} required/><button><Plus/> Add Location</button></form><div className="vm-location-list">{data.locations.map((item:any)=><div key={item.id}><span><b>{item.name}</b><small>{item.vehicle_count} vehicles</small></span><button aria-label={`Rename ${item.name}`} onClick={async()=>{const next=prompt("Rename location",item.name);if(!next||next===item.name)return;try{await api(`/api/private/vehicles/locations/${item.id}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:next})});await load()}catch(error:any){setMessage(error.message)}}}><Pencil/></button><button aria-label={`Delete ${item.name}`} className="danger" onClick={()=>remove(item)}><Trash2/></button></div>)}</div></article>}
  {view==="sharing"&&<><article className="vm-settings-card vm-add-user" id="sharing"><UserPlus/><h2>Add User</h2><p>Create a restricted driver/employee login and assign its vehicle access.</p><form onSubmit={createUser}><div className="vm-user-fields"><label>Full Name *<input required value={newUser.name} onChange={event=>setNewUser({...newUser,name:event.target.value})}/></label><label>Email *<input type="email" required value={newUser.email} onChange={event=>setNewUser({...newUser,email:event.target.value})}/></label><label>Mobile Number<input value={newUser.mobile} onChange={event=>setNewUser({...newUser,mobile:event.target.value})}/></label><label>Password <small>(leave blank to generate)</small><input type="password" minLength={12} value={newUser.password} onChange={event=>setNewUser({...newUser,password:event.target.value})}/></label><label>Role<select value={newUser.permission} onChange={event=>setNewUser({...newUser,permission:event.target.value})}><option value="view">Viewer</option><option value="editor">Editor</option></select></label><label>Location Access<select value={newUser.scope} onChange={event=>setNewUser({...newUser,scope:event.target.value,vehicleIds:[]})}><option value="location">Entire Location</option><option value="selected">Selected Vehicles</option></select></label><label>Location<select required value={newUser.locationId} onChange={event=>setNewUser({...newUser,locationId:event.target.value,vehicleIds:[]})}><option value="">Select Location</option>{sharing.locations.map((location:any)=><option key={location.id} value={location.id}>{location.name}</option>)}</select></label></div>{newUser.scope==="selected"&&<fieldset className="vm-share-vehicles"><legend>Select Vehicles</legend>{newUserVehicles.map((vehicle:any)=><label key={vehicle.id}><input type="checkbox" checked={newUser.vehicleIds.includes(vehicle.id)} onChange={event=>setNewUser({...newUser,vehicleIds:event.target.checked?[...newUser.vehicleIds,vehicle.id]:newUser.vehicleIds.filter(id=>id!==vehicle.id)})}/><span><b>{vehicle.vehicle_number}</b><small>{[vehicle.vehicle_name,vehicle.type].filter(Boolean).join(" · ")}</small></span></label>)}{!newUserVehicles.length&&<p>No vehicles are available for this location.</p>}</fieldset>}<button disabled={saving}><UserPlus/> {saving?"Creating…":"Create User"}</button></form></article>
  <article className="vm-settings-card vm-sharing-card"><Share2/><h2>Manage Access</h2><p>Edit an existing user's role, location or selected vehicles.</p><form onSubmit={saveShare}><label>User<select required value={share.granteeUserId} onChange={event=>setShare({...share,granteeUserId:event.target.value})}><option value="">Select user</option>{sharing.users.map((user:any)=><option key={user.id} value={user.id}>{user.name} — {user.email}</option>)}</select></label><label>Location<select required value={share.locationId} onChange={event=>setShare({...share,locationId:event.target.value,vehicleIds:[]})}><option value="">Select location</option>{sharing.locations.map((location:any)=><option key={location.id} value={location.id}>{location.name}</option>)}</select></label><div className="vm-share-options"><label>Permission<select value={share.permission} onChange={event=>setShare({...share,permission:event.target.value})}><option value="view">View Only</option><option value="editor">Editor</option></select></label><label>Access Scope<select value={share.scope} onChange={event=>setShare({...share,scope:event.target.value,vehicleIds:event.target.value==="location"?[]:share.vehicleIds})}><option value="location">Entire Location</option><option value="selected">Selected Vehicles</option></select></label></div>{share.scope==="selected"&&<fieldset className="vm-share-vehicles"><legend>Select vehicles</legend>{availableVehicles.map((vehicle:any)=><label key={vehicle.id}><input type="checkbox" checked={share.vehicleIds.includes(vehicle.id)} onChange={event=>setShare({...share,vehicleIds:event.target.checked?[...share.vehicleIds,vehicle.id]:share.vehicleIds.filter(id=>id!==vehicle.id)})}/><span><b>{vehicle.vehicle_number}</b><small>{[vehicle.vehicle_name,vehicle.type].filter(Boolean).join(" · ")}</small></span></label>)}{!availableVehicles.length&&<p>No vehicles are available for this location.</p>}</fieldset>}<div className="vm-share-submit"><button disabled={saving}>{saving?"Saving…":share.id?"Save Access":"Assign Access"}</button>{!!share.id&&<button type="button" className="secondary" onClick={()=>setShare(emptyShare)}>Cancel</button>}</div></form></article>
  <article className="vm-settings-card vm-managed-users"><Share2/><h2>Sharing & Users</h2><div className="vm-managed-table"><div className="head"><b>User</b><b>Role / Access</b><b>Status</b><b>Last Login</b><b>Created</b><b>Actions</b></div>{sharing.managedUsers.map((item:any)=><div key={`${item.id}-${item.share_id||"none"}`}><span><b>{item.name}</b><small>{item.email}{item.mobile?` · ${item.mobile}`:""}</small></span><span><b>{item.permission==="editor"?"Editor":"Viewer"}</b><small>{item.location_name||"No access"} · {item.share_id?(item.scope==="selected"?`${item.vehicle_count} selected vehicles`:"Entire location"):"Revoked"}</small></span><span><b>{item.active?"Active":"Disabled"}</b><small>{item.invitation_status||"Not sent"}</small></span><span>{item.last_login_at||"Never"}</span><span>{item.created_at||"—"}</span><div className="actions">{item.share_id&&<button onClick={()=>{const found=sharing.shares.find((value:any)=>value.id===item.share_id);if(found)editShare(found)}}>View/Edit Access</button>}<button disabled={!item.share_id} onClick={()=>userAction(item.id,"resend-invitation")}><Mail/> Resend</button><button disabled={!item.share_id} onClick={()=>userAction(item.id,"reset-password")}><RotateCcw/> Reset Password</button><button onClick={()=>userAction(item.id,"",!item.active)}><Power/> {item.active?"Disable":"Enable"}</button>{item.share_id&&<button className="danger" onClick={()=>revoke(item.share_id)}>Revoke Access</button>}</div></div>)}{!sharing.managedUsers.length&&<p>No sharing users created yet.</p>}</div></article></>}
  </>}
  {message&&<div className="vm-error">{message}</div>}
 </section></main>;
}

export function VehiclePasswordReset(){const token=new URLSearchParams(location.search).get("reset")||"",[message,setMessage]=useState("");return <main className="vm vm-login"><form onSubmit={async event=>{event.preventDefault();const values=Object.fromEntries(new FormData(event.currentTarget));if(values.password!==values.confirmPassword){setMessage("Passwords do not match");return}try{await api("/api/auth/reset-password",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({token,password:values.password})});setMessage("Password reset. You can now sign in.")}catch(error:any){setMessage(error.message)}}}><div className="vm-login-brand"><img src="/pwa/icon-192.png" alt="" aria-hidden="true"/><span><b>GaadiFile</b><small>Your Vehicle, All in One Place</small></span></div><h1>Reset password</h1><p>This secure link expires after 30 minutes.</p><input name="password" type="password" minLength={12} placeholder="New password" required/><input name="confirmPassword" type="password" minLength={12} placeholder="Confirm new password" required/>{message&&<div className="vm-error">{message}</div>}<button>Reset password</button><a href="/vehicles">Back to login</a></form></main>}
