import {useState} from "react";
import {ArrowLeft,Download} from "lucide-react";

async function api(url:string,options?:RequestInit){const r=await fetch(url,options),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Request failed");return d}
export function VehicleImport(){
 const[preview,setPreview]=useState<any>(null),[mode,setMode]=useState("skip"),[createLocations,setCreateLocations]=useState(true),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 const previewFile=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);setMessage("");try{setPreview(await api("/api/private/vehicles/import/preview",{method:"POST",body:new FormData(e.currentTarget)}))}catch(x:any){setMessage(x.message)}finally{setBusy(false)}};
 const commit=async()=>{setBusy(true);try{const result=await api("/api/private/vehicles/import/commit",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({duplicateMode:mode,createMissingLocations:createLocations,rows:preview.rows})});setMessage(`Created ${result.created}, updated ${result.updated}, skipped ${result.skipped}.`);setPreview(null)}catch(x:any){setMessage(x.message)}finally{setBusy(false)}};
 return <main className="vm vm-import"><header><div><img className="vm-header-brand-logo" src="/pwa/icon-192.png" alt="" aria-hidden="true"/><span><b>GaadiFile</b><small>Import vehicles · CSV or Excel</small></span></div><a href="/vehicles"><ArrowLeft/> My vehicles</a></header><section className="vm-wrap"><div className="vm-title"><div><small>IMPORT</small><h1>Import vehicle list</h1><p>Download the template, fill in your vehicle details, save the file, then upload it here.</p></div></div><div className="vm-template-actions"><a className="vm-button primary" href="/api/private/vehicles/import/template.xlsx"><Download/> Download Excel Template (.xlsx)</a><a className="vm-button secondary" href="/api/private/vehicles/import/template.csv"><Download/> Download CSV Template (.csv)</a></div><form className="vm-import-form" onSubmit={previewFile}><label><b>Choose Excel File</b><input name="file" type="file" accept=".xlsx,.csv" required/></label><button disabled={busy}>{busy?"Validating…":"Preview import"}</button></form>{message&&<div className="vm-error">{message}</div>}{preview&&<><div className="vm-stats"><article><small>Valid rows</small><strong>{preview.valid}</strong></article><article><small>Invalid rows</small><strong>{preview.invalid}</strong></article><article><small>Duplicates</small><strong>{preview.duplicates}</strong></article></div><div className="vm-import-options"><b>Existing vehicle numbers:</b><label><input type="radio" checked={mode==="skip"} onChange={()=>setMode("skip")}/> Skip duplicates</label><label><input type="radio" checked={mode==="update"} onChange={()=>setMode("update")}/> Update existing</label></div><div className="vm-import-table"><div className="vm-import-row head"><b>Row</b><b>Vehicle</b><b>Type</b><b>Brand / Model</b><b>Status</b></div>{preview.rows.map((r:any)=><div className={`vm-import-row ${r.valid?"valid":"invalid"}`} key={r.row}><span>{r.row}</span><span>{r.data.vehicle_number}</span><span>{r.data.type}</span><span>{r.data.make} {r.data.model}</span><span>{r.error||r.warning||"Ready"}</span></div>)}</div><button disabled={busy||!preview.valid} onClick={commit}>Import valid rows</button></>}</section></main>
}
